# Generated by Django 6.0 on 2025-12-14 13:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('idCliente', models.AutoField(primary_key=True, serialize=False)),
                ('rutCliente', models.IntegerField()),
                ('dvCliente', models.IntegerField()),
                ('nombreCliente', models.CharField(max_length=100)),
                ('telCliente', models.CharField(max_length=15)),
                ('emailCliente', models.EmailField(max_length=254)),
                ('direccion', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Mascota',
            fields=[
                ('idMascota', models.AutoField(primary_key=True, serialize=False)),
                ('nombreMascota', models.CharField(max_length=100)),
                ('animal_mascota', models.CharField(max_length=50)),
                ('raza_mascota', models.CharField(max_length=50)),
                ('edad', models.IntegerField()),
                ('peso', models.FloatField()),
                ('idCliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.cliente')),
            ],
        ),
        migrations.CreateModel(
            name='DocumentoMascota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(upload_to='documentos_mascota/')),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
                ('mascota', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='gestion.mascota')),
            ],
        ),
        migrations.CreateModel(
            name='Consulta',
            fields=[
                ('idConsulta', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_consulta', models.DateField()),
                ('motivo_consulta', models.TextField()),
                ('diagnostico', models.CharField(max_length=255)),
                ('tratamiento', models.CharField(max_length=100)),
                ('veterinario', models.CharField(max_length=60)),
                ('idMascota', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.mascota')),
            ],
        ),
        migrations.CreateModel(
            name='Agenda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_agenda', models.DateField()),
                ('hora_agenda', models.TimeField()),
                ('nombreMascota', models.CharField(max_length=100)),
                ('nombre_apellido', models.CharField(max_length=100)),
                ('telefono', models.CharField(max_length=15)),
                ('razon', models.CharField(max_length=100)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('confirmada', 'Confirmada'), ('cancelada', 'Cancelada')], default='pendiente', max_length=20)),
                ('idMascota', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.mascota')),
            ],
            options={
                'unique_together': {('nombreMascota', 'fecha_agenda', 'hora_agenda')},
            },
        ),
    ]
