# Generated by Django 5.2.7 on 2025-11-17 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documentomascota',
            name='mascota',
        ),
        migrations.DeleteModel(
            name='Agenda',
        ),
        migrations.DeleteModel(
            name='DocumentoMascota',
        ),
    ]
