# Generated by Django 5.2.5 on 2025-11-17 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0002_mascota_sexo'),
    ]

    operations = [
        migrations.AddField(
            model_name='mascota',
            name='chip',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
