# Generated by Django 5.2.7 on 2025-12-09 03:37

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Insumo',
            fields=[
                ('idInventario', models.AutoField(primary_key=True, serialize=False)),
                ('medicamento', models.CharField(max_length=200)),
                ('sku', models.CharField(blank=True, max_length=100, null=True)),
                ('especie', models.CharField(blank=True, max_length=50, null=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('ml_contenedor', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='ML en Contenedor')),
                ('tipo', models.CharField(blank=True, max_length=50, null=True, verbose_name='Tipo de Producto')),
                ('precio_venta', models.FloatField(default=0)),
                ('stock_actual', models.IntegerField(default=0)),
                ('precauciones', models.TextField(blank=True, null=True)),
                ('contraindicaciones', models.TextField(blank=True, null=True)),
                ('efectos_adversos', models.TextField(blank=True, null=True)),
                ('dosis_ml', models.FloatField(blank=True, null=True)),
                ('peso_kg', models.FloatField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de Registro')),
                ('ultimo_ingreso', models.DateTimeField(blank=True, null=True)),
                ('ultimo_movimiento', models.DateTimeField(blank=True, null=True)),
                ('tipo_ultimo_movimiento', models.CharField(blank=True, choices=[('entrada', 'Entrada de Stock'), ('salida', 'Salida de Stock'), ('venta', 'Venta'), ('consulta', 'Uso en Consulta'), ('hospitalizacion', 'Uso en Hospitalización'), ('ajuste_manual', 'Ajuste Manual'), ('devolucion', 'Devolución'), ('registro_inicial', 'Registro Inicial')], max_length=20, null=True)),
                ('usuario_ultimo_movimiento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimientos_insumos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Insumo',
                'ordering': ['medicamento'],
            },
        ),
    ]
