# Generated by Django 6.0 on 2025-12-14 13:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Insumo',
            fields=[
                ('idInventario', models.AutoField(primary_key=True, serialize=False)),
                ('medicamento', models.CharField(max_length=255)),
                ('marca', models.CharField(blank=True, max_length=100, null=True)),
                ('sku', models.CharField(blank=True, max_length=100, null=True)),
                ('tipo', models.CharField(blank=True, max_length=100, null=True)),
                ('formato', models.CharField(blank=True, choices=[('liquido', 'Líquido'), ('pastilla', 'Pastilla'), ('pipeta', 'Pipeta'), ('inyectable', 'Inyectable'), ('polvo', 'Polvo'), ('crema', 'Crema'), ('otro', 'Otro')], max_length=50, null=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('especie', models.CharField(blank=True, max_length=100, null=True)),
                ('stock_actual', models.IntegerField(default=0)),
                ('stock_minimo', models.IntegerField(default=10, help_text='Nivel mínimo de stock (rojo)')),
                ('stock_medio', models.IntegerField(default=20, help_text='Nivel medio de stock (naranja)')),
                ('precio_venta', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('archivado', models.BooleanField(default=False, help_text='Producto archivado (no se muestra en listado activo)')),
                ('dosis_ml', models.DecimalField(blank=True, decimal_places=2, help_text='Dosis en ml (para líquidos)', max_digits=10, null=True)),
                ('ml_contenedor', models.DecimalField(blank=True, decimal_places=2, help_text='ML por contenedor', max_digits=10, null=True)),
                ('cantidad_pastillas', models.IntegerField(blank=True, help_text='Cantidad de pastillas', null=True)),
                ('unidades_pipeta', models.IntegerField(blank=True, help_text='Unidades de pipeta', null=True)),
                ('peso_kg', models.DecimalField(blank=True, decimal_places=2, help_text='Peso de referencia en kg', max_digits=10, null=True)),
                ('tiene_rango_peso', models.BooleanField(default=False, help_text='¿Tiene rango de peso específico?')),
                ('peso_min_kg', models.DecimalField(blank=True, decimal_places=2, help_text='Peso mínimo en kg', max_digits=10, null=True)),
                ('peso_max_kg', models.DecimalField(blank=True, decimal_places=2, help_text='Peso máximo en kg', max_digits=10, null=True)),
                ('precauciones', models.TextField(blank=True, null=True)),
                ('contraindicaciones', models.TextField(blank=True, null=True)),
                ('efectos_adversos', models.TextField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, null=True)),
                ('ultimo_ingreso', models.DateTimeField(blank=True, null=True)),
                ('ultimo_movimiento', models.DateTimeField(blank=True, null=True)),
                ('tipo_ultimo_movimiento', models.CharField(blank=True, choices=[('entrada', 'Entrada'), ('salida', 'Salida'), ('registro_inicial', 'Registro Inicial')], max_length=20, null=True)),
                ('usuario_ultimo_movimiento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Insumo',
                'verbose_name_plural': 'Insumos',
                'db_table': 'inventario',
                'ordering': ['medicamento'],
            },
        ),
    ]
