# Generated by Django 5.2.7 on 2025-12-09 04:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='insumo',
            options={'managed': False},
        ),
    ]
