# Generated by Django 6.0 on 2025-12-17 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insumo',
            name='especie',
            field=models.CharField(blank=True, choices=[('canino', 'Canino'), ('felino', 'Felino'), ('ambos', 'Ambos'), ('otro', 'Otro')], max_length=100, null=True),
        ),
    ]
