# Generated by Django 6.0 on 2025-12-17 11:44

from django.db import migrations


def actualizar_especies_insumos(apps, schema_editor):
    """Actualizar valores de especie de perro/gato a canino/felino"""
    Insumo = apps.get_model('inventario', 'Insumo')
    
    # Actualizar perro -> canino
    Insumo.objects.filter(especie__iexact='perro').update(especie='canino')
    
    # Actualizar gato -> felino
    Insumo.objects.filter(especie__iexact='gato').update(especie='felino')
    
    # Actualizar variantes de "ambos/todos"
    Insumo.objects.filter(especie__iexact='todos').update(especie='ambos')
    Insumo.objects.filter(especie__iexact='todas').update(especie='ambos')
    Insumo.objects.filter(especie__iexact='ambas').update(especie='ambos')
    
    print("✅ Especies de insumos actualizadas: perro→canino, gato→felino, todos→ambos")


def revertir_especies_insumos(apps, schema_editor):
    """Revertir valores de especie de canino/felino a perro/gato"""
    Insumo = apps.get_model('inventario', 'Insumo')
    
    # Revertir canino -> perro
    Insumo.objects.filter(especie='canino').update(especie='perro')
    
    # Revertir felino -> gato
    Insumo.objects.filter(especie='felino').update(especie='gato')
    
    # Revertir ambos -> todos
    Insumo.objects.filter(especie='ambos').update(especie='todos')
    
    print("✅ Especies de insumos revertidas: canino→perro, felino→gato, ambos→todos")


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0002_alter_insumo_especie'),
    ]

    operations = [
        migrations.RunPython(actualizar_especies_insumos, revertir_especies_insumos),
    ]
