# Generated by Django 5.2.7 on 2025-12-09 04:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0002_alter_insumo_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='insumo',
            options={'managed': True},
        ),
    ]
