# Generated by Django 5.2.7 on 2025-12-09 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0003_alter_insumo_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='insumo',
            name='contraindicaciones',
        ),
        migrations.RemoveField(
            model_name='insumo',
            name='descripcion',
        ),
        migrations.RemoveField(
            model_name='insumo',
            name='dosis_ml',
        ),
        migrations.RemoveField(
            model_name='insumo',
            name='efectos_adversos',
        ),
        migrations.RemoveField(
            model_name='insumo',
            name='especie',
        ),
        migrations.RemoveField(
            model_name='insumo',
            name='fecha_creacion',
        ),
        migrations.RemoveField(
            model_name='insumo',
            name='ml_contenedor',
        ),
        migrations.RemoveField(
            model_name='insumo',
            name='peso_kg',
        ),
        migrations.RemoveField(
            model_name='insumo',
            name='precauciones',
        ),
        migrations.RemoveField(
            model_name='insumo',
            name='sku',
        ),
        migrations.RemoveField(
            model_name='insumo',
            name='tipo',
        ),
        migrations.RemoveField(
            model_name='insumo',
            name='tipo_ultimo_movimiento',
        ),
        migrations.RemoveField(
            model_name='insumo',
            name='ultimo_ingreso',
        ),
        migrations.RemoveField(
            model_name='insumo',
            name='ultimo_movimiento',
        ),
        migrations.RemoveField(
            model_name='insumo',
            name='usuario_ultimo_movimiento',
        ),
        migrations.AlterField(
            model_name='insumo',
            name='medicamento',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='insumo',
            name='precio_venta',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterModelTable(
            name='insumo',
            table='inventario',
        ),
    ]
