# Generated by Django 6.0 on 2025-12-17 11:56

from django.db import migrations


def normalizar_especies_minusculas(apps, schema_editor):
    """Normalizar valores de especie a minúsculas"""
    Insumo = apps.get_model('inventario', 'Insumo')
    
    # Actualizar cualquier valor con mayúsculas a minúsculas
    # Esto maneja casos como "Otro", "OTRO", "Canino", etc.
    insumos = Insumo.objects.all()
    actualizados = 0
    
    for insumo in insumos:
        if insumo.especie:
            especie_normalizada = insumo.especie.lower()
            if insumo.especie != especie_normalizada:
                insumo.especie = especie_normalizada
                insumo.save()
                actualizados += 1
    
    print(f"✅ {actualizados} especies normalizadas a minúsculas")


def revertir_normalizacion(apps, schema_editor):
    """Revertir normalización (no hace nada, ya que no podemos saber el formato original)"""
    print("⚠️ No se puede revertir la normalización automáticamente")


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0003_actualizar_especies_a_canino_felino'),
    ]

    operations = [
        migrations.RunPython(normalizar_especies_minusculas, revertir_normalizacion),
    ]
