# Generated by Django 5.2.7 on 2025-12-09 04:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0004_remove_insumo_contraindicaciones_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='insumo',
            options={'ordering': ['medicamento'], 'verbose_name': 'Insumo', 'verbose_name_plural': 'Insumos'},
        ),
        migrations.AddField(
            model_name='insumo',
            name='contraindicaciones',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='insumo',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='insumo',
            name='dosis_ml',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Dosis en ml', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='insumo',
            name='efectos_adversos',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='insumo',
            name='especie',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='insumo',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='insumo',
            name='ml_contenedor',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='ML por contenedor', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='insumo',
            name='peso_kg',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Peso de referencia en kg', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='insumo',
            name='precauciones',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='insumo',
            name='sku',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='insumo',
            name='tipo',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='insumo',
            name='tipo_ultimo_movimiento',
            field=models.CharField(blank=True, choices=[('entrada', 'Entrada'), ('salida', 'Salida'), ('registro_inicial', 'Registro Inicial')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='insumo',
            name='ultimo_ingreso',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='insumo',
            name='ultimo_movimiento',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='insumo',
            name='usuario_ultimo_movimiento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
