# Generated by Django 6.0 on 2025-12-17 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0004_normalizar_especies_minusculas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insumo',
            name='tipo_ultimo_movimiento',
            field=models.CharField(blank=True, choices=[('ingreso_stock', 'Ingreso de Stock'), ('salida_stock', 'Salida de Stock'), ('modificacion_informacion', 'Modificación de Información'), ('actualizacion_precio', 'Actualización de Precio')], max_length=30, null=True),
        ),
    ]
