# Generated by Django 6.0 on 2025-12-17 12:05

from django.db import migrations


def actualizar_tipos_movimiento(apps, schema_editor):
    """Actualiza los valores antiguos a los nuevos tipos de movimiento"""
    Insumo = apps.get_model('inventario', 'Insumo')
    
    # Mapeo de valores antiguos a nuevos
    mapeo = {
        'entrada': 'ingreso_stock',
        'salida': 'salida_stock',
        # registro_inicial se mantiene como None ya que no está en las nuevas opciones
    }
    
    actualizados = 0
    for insumo in Insumo.objects.all():
        if insumo.tipo_ultimo_movimiento in mapeo:
            insumo.tipo_ultimo_movimiento = mapeo[insumo.tipo_ultimo_movimiento]
            insumo.save()
            actualizados += 1
        elif insumo.tipo_ultimo_movimiento == 'registro_inicial':
            # Para registros iniciales, mantenerlos como None o asignar un valor por defecto
            insumo.tipo_ultimo_movimiento = None
            insumo.save()
            actualizados += 1
    
    print(f"✅ {actualizados} tipos de movimiento actualizados")


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0005_alter_insumo_tipo_ultimo_movimiento'),
    ]

    operations = [
        migrations.RunPython(actualizar_tipos_movimiento, migrations.RunPython.noop),
    ]
