# Generated by Django 5.2.7 on 2025-12-09 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0005_alter_insumo_options_insumo_contraindicaciones_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='insumo',
            name='cantidad_pastillas',
            field=models.IntegerField(blank=True, help_text='Cantidad de pastillas', null=True),
        ),
        migrations.AddField(
            model_name='insumo',
            name='formato',
            field=models.CharField(blank=True, choices=[('liquido', 'Líquido'), ('pastilla', 'Pastilla'), ('pipeta', 'Pipeta'), ('inyectable', 'Inyectable'), ('polvo', 'Polvo'), ('crema', 'Crema'), ('otro', 'Otro')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='insumo',
            name='marca',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='insumo',
            name='peso_max_kg',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Peso máximo en kg', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='insumo',
            name='peso_min_kg',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Peso mínimo en kg', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='insumo',
            name='tiene_rango_peso',
            field=models.BooleanField(default=False, help_text='¿Tiene rango de peso específico?'),
        ),
        migrations.AddField(
            model_name='insumo',
            name='unidades_pipeta',
            field=models.IntegerField(blank=True, help_text='Unidades de pipeta', null=True),
        ),
        migrations.AlterField(
            model_name='insumo',
            name='dosis_ml',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Dosis en ml (para líquidos)', max_digits=10, null=True),
        ),
    ]
