# Generated by Django 5.2.7 on 2025-12-12 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0006_insumo_cantidad_pastillas_insumo_formato_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='insumo',
            name='stock_medio',
            field=models.IntegerField(default=20, help_text='Nivel medio de stock (naranja)'),
        ),
        migrations.AddField(
            model_name='insumo',
            name='stock_minimo',
            field=models.IntegerField(default=10, help_text='Nivel mínimo de stock (rojo)'),
        ),
    ]
