# Generated by Django 5.2.7 on 2025-12-12 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0007_insumo_stock_medio_insumo_stock_minimo'),
    ]

    operations = [
        migrations.AddField(
            model_name='insumo',
            name='archivado',
            field=models.BooleanField(default=False, help_text='Producto archivado (no se muestra en listado activo)'),
        ),
    ]
