"""
Django settings for veteriaria project.

Generated by 'django-admin startproject' using Django 5.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""
#settings para desarrollo local
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-200*b%=5$zj5po94p#aref=mkjv=ny4xql6uos(o*-lt4!pygq'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'jazzmin',
    
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.humanize',
    'django_extensions',
    'historial',  # Sistema de auditoría y trazabilidad
    'dashboard',
    'caja',
    'inventario',
    'servicios',  
    'pacientes',
    'clinica',    
    'login',
    'cuentas',
    'agenda',
    'reportes',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'historial.middleware.CurrentUserMiddleware',  # Captura el usuario actual para signals
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'veteriaria.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
            BASE_DIR / 'templates',  # Carpeta de templates global
            BASE_DIR / 'dashboard' / 'templates',  # Templates del dashboard
        ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'veteriaria.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'veterinaria_db',
        'USER': 'veterinaria_user',
        'PASSWORD': 'Veterinaria2025*',
        'HOST': 'localhost',
        'PORT': '5432',
    }
}



# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'es-cl'

TIME_ZONE = 'America/Santiago'

USE_I18N = True

USE_TZ = True

APPEND_SLASH = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = '/static/'

STATICFILES_DIRS = [
    BASE_DIR / 'static',  # Carpeta static global
      BASE_DIR / 'agenda/Static',
]

STATIC_ROOT = BASE_DIR / 'staticfiles'

# Media files (Uploaded files)
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
AUTH_USER_MODEL = 'cuentas.CustomUser'
AUTHENTICATION_BACKENDS = ['cuentas.auth_backend.RUTAuthBackend']



# Login/Logout URLs
LOGIN_URL = 'login'  # Cambiado de '/login/' a 'login'
LOGIN_REDIRECT_URL = '/dashboard/'
LOGOUT_REDIRECT_URL = 'login'  # Cambiado de '/login/' a 'login'

AUTHENTICATION_BACKENDS = [
    'cuentas.backends.RutBackend',  # Backend personalizado para RUT
    'django.contrib.auth.backends.ModelBackend',  # Backend por defecto
]

JAZZMIN_SETTINGS = {
    # =========================
    # Branding
    # =========================
    "site_title": "VetSantaSofia Admin",
    "site_header": "Veterinaria Santa Sofía",
    "site_brand": "VetSantaSofia",
    "welcome_sign": "Administración Clínica Veterinaria",
    "copyright": "Veterinaria Santa Sofía",

    # Logo (opcional, puedes dejar None)
    "site_logo": None,
    "login_logo": None,
    "site_icon": None,

    # =========================
    # Navegación
    # =========================
    "show_sidebar": True,
    "navigation_expanded": True,

    # Orden lógico por flujo real del sistema
    "order_with_respect_to": [
    "agenda",
    "clinica",
    "pacientes",
    "inventario",
    "servicios",
    "auth",
],


    # Ocultar modelos técnicos
    "hide_models": [
        "auth.permission",
        "contenttypes.contenttype",
        "admin.logentry",
        "sessions.session",
    ],

    # =========================
    # Íconos semánticos
    # =========================
    "icons": {
     # =========================
    # Agenda
    # =========================
    "agenda": "fas fa-calendar-alt",
    "agenda.cita": "fas fa-clock",
    "agenda.excepciondisponibilidad": "fas fa-ban",
    "agenda.horariofijoveterinario": "fas fa-calendar-day",

    # =========================
    # Clínica
    # =========================
    "clinica": "fas fa-stethoscope",
    "clinica.consulta": "fas fa-notes-medical",
    "clinica.cirugia": "fas fa-procedures",
    "clinica.hospitalizacion": "fas fa-hospital",
    "clinica.altamedica": "fas fa-file-medical",
    "clinica.documento": "fas fa-file-medical-alt",
    "clinica.registrodiario": "fas fa-clipboard-list",

    # =========================
    # Pacientes
    # =========================
    "pacientes": "fas fa-paw",
    "pacientes.paciente": "fas fa-dog",
    "pacientes.propietario": "fas fa-user",

    # =========================
    # Inventario
    # =========================
    "inventario": "fas fa-boxes",
    "inventario.insumo": "fas fa-pills",

    # =========================
    # Servicios
    # =========================
    "servicios": "fas fa-concierge-bell",
    "servicios.servicioveterinario": "fas fa-briefcase-medical",
    "servicios.servicioinsumo": "fas fa-syringe",

    # =========================
    # Autenticación
    # =========================
    "auth": "fas fa-user-shield",
    "auth.group": "fas fa-users-cog",
    "cuentas.customuser": "fas fa-user-md",

    # =========================
    # Auditoría
    # =========================
    "admin.logentry": "fas fa-history",
},


    "default_icon_parents": "fas fa-folder",
    "default_icon_children": "fas fa-file",

    # =========================
    # Formularios
    # =========================
    "changeform_format": "horizontal_tabs",

    "changeform_format_overrides": {
        "auth.user": "collapsible",
        "auth.group": "vertical_tabs",
        "inventario.insumo": "horizontal_tabs",
        "clinica.consulta": "horizontal_tabs",
        "hospital.hospitalizacion": "horizontal_tabs",
    },

    # =========================
    # UX y rendimiento
    # =========================
    "show_ui_builder": True,
    "related_modal_active": False,

    # =========================
    # Colores
    # =========================
    "theme": "litera",
    "use_google_fonts_cdn": True,
    "custom_css": "css/base/jazzmin_fixes.css",
}

JAZZMIN_UI_TWEAKS = {
    "navbar_small_text": False,
    "footer_small_text": False,
    "body_small_text": False,
    "brand_small_text": False,
    "brand_colour": False,
    "accent": "accent-primary",
    "navbar": "navbar-white navbar-light",
    "no_navbar_border": False,
    "navbar_fixed": False,
    "layout_boxed": False,
    "footer_fixed": False,
    "sidebar_fixed": True,
    "sidebar": "sidebar-dark-primary",
    "sidebar_nav_small_text": False,
    "sidebar_disable_expand": True,
    "sidebar_nav_child_indent": True,
    "sidebar_nav_compact_style": True,
    "sidebar_nav_legacy_style": True,
    "sidebar_nav_flat_style": True,
    "theme": "litera",
    "dark_mode_theme": None,
    "button_classes": {
        "primary": "btn-outline-primary",
        "secondary": "btn-outline-secondary",
        "info": "btn-info",
        "warning": "btn-warning",
        "danger": "btn-danger",
        "success": "btn-success"
    }
}