# Generated by Django 6.0 on 2025-12-14 13:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pacientes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DisponibilidadBloquesDia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('trabaja', models.BooleanField(default=True)),
                ('rangos', models.JSONField(default=list, help_text='Lista de dicts {"start_block": int, "end_block": int}')),
                ('notas', models.TextField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Disponibilidad diaria (bloques)',
                'verbose_name_plural': 'Disponibilidades diarias (bloques)',
                'ordering': ['fecha'],
            },
        ),
        migrations.CreateModel(
            name='DisponibilidadVeterinario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField()),
                ('tipo', models.CharField(choices=[('vacaciones', 'Vacaciones'), ('licencia', 'Licencia'), ('ausencia', 'Ausencia'), ('disponible_extra', 'Disponibilidad Extra')], default='vacaciones', max_length=20)),
                ('notas', models.TextField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Excepción de Disponibilidad',
                'verbose_name_plural': 'Excepciones de Disponibilidad',
                'ordering': ['fecha', 'hora_inicio'],
            },
        ),
        migrations.CreateModel(
            name='HorarioFijoVeterinario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia_semana', models.IntegerField(choices=[(0, 'Lunes'), (1, 'Martes'), (2, 'Miércoles'), (3, 'Jueves'), (4, 'Viernes'), (5, 'Sábado'), (6, 'Domingo')])),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField()),
                ('activo', models.BooleanField(default=True)),
                ('notas', models.TextField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Horario Fijo de Veterinario',
                'verbose_name_plural': 'Horarios Fijos de Veterinarios',
                'ordering': ['veterinario', 'dia_semana', 'hora_inicio'],
            },
        ),
        migrations.CreateModel(
            name='Cita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField(blank=True, null=True)),
                ('start_block', models.PositiveSmallIntegerField(blank=True, help_text='Índice de bloque de inicio (0-95)', null=True)),
                ('end_block', models.PositiveSmallIntegerField(blank=True, help_text='Índice de bloque fin exclusivo (1-96)', null=True)),
                ('tipo', models.CharField(choices=[('consulta', 'Consulta General'), ('vacunacion', 'Vacunación'), ('cirugia', 'Cirugía'), ('control', 'Control'), ('emergencia', 'Emergencia'), ('peluqueria', 'Peluquería'), ('otro', 'Otro')], default='consulta', max_length=20)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('confirmada', 'Confirmada'), ('en_curso', 'En Curso'), ('completada', 'Completada'), ('cancelada', 'Cancelada'), ('no_asistio', 'No Asistió')], default='pendiente', max_length=20)),
                ('motivo', models.TextField()),
                ('notas', models.TextField(blank=True, null=True)),
                ('recordatorio_enviado', models.BooleanField(default=False)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='citas', to='pacientes.paciente')),
            ],
            options={
                'verbose_name': 'Cita',
                'verbose_name_plural': 'Citas',
                'ordering': ['fecha', 'hora_inicio'],
            },
        ),
    ]
