# Generated by Django 5.2.7 on 2025-11-17 09:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gestion', '0002_remove_documentomascota_mascota_delete_agenda_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agenda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_agenda', models.DateField()),
                ('hora_agenda', models.TimeField()),
                ('nombreMascota', models.CharField(max_length=100)),
                ('nombre_apellido', models.CharField(max_length=100)),
                ('telefono', models.IntegerField()),
                ('razon', models.CharField(max_length=100)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('confirmada', 'Confirmada'), ('cancelada', 'Cancelada')], default='pendiente', max_length=20)),
                ('idMascota', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.mascota')),
            ],
            options={
                'unique_together': {('nombreMascota', 'fecha_agenda', 'hora_agenda')},
            },
        ),
    ]
