# Generated by Django 6.0 on 2025-12-14 13:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agenda', '0001_initial'),
        ('servicios', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='cita',
            name='servicio',
            field=models.ForeignKey(blank=True, help_text='Servicio asociado a la cita', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='citas', to='servicios.servicio'),
        ),
        migrations.AddField(
            model_name='cita',
            name='veterinario',
            field=models.ForeignKey(limit_choices_to={'rol': 'veterinario'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='citas_asignadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='disponibilidadbloquesdia',
            name='veterinario',
            field=models.ForeignKey(limit_choices_to={'rol': 'veterinario'}, on_delete=django.db.models.deletion.CASCADE, related_name='disponibilidades_bloques', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='disponibilidadveterinario',
            name='veterinario',
            field=models.ForeignKey(limit_choices_to={'rol': 'veterinario'}, on_delete=django.db.models.deletion.CASCADE, related_name='disponibilidades', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='horariofijoveterinario',
            name='veterinario',
            field=models.ForeignKey(limit_choices_to={'rol': 'veterinario'}, on_delete=django.db.models.deletion.CASCADE, related_name='horarios_fijos', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='cita',
            index=models.Index(fields=['fecha', 'estado'], name='agenda_cita_fecha_86b79d_idx'),
        ),
        migrations.AddIndex(
            model_name='cita',
            index=models.Index(fields=['veterinario', 'fecha'], name='agenda_cita_veterin_4389cc_idx'),
        ),
        migrations.AddIndex(
            model_name='cita',
            index=models.Index(fields=['veterinario', 'fecha', 'start_block'], name='agenda_cita_veterin_b68f08_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='cita',
            unique_together={('veterinario', 'fecha', 'hora_inicio')},
        ),
        migrations.AddIndex(
            model_name='disponibilidadbloquesdia',
            index=models.Index(fields=['veterinario', 'fecha'], name='agenda_disp_veterin_cfb6df_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='disponibilidadbloquesdia',
            unique_together={('veterinario', 'fecha')},
        ),
        migrations.AddIndex(
            model_name='disponibilidadveterinario',
            index=models.Index(fields=['veterinario', 'fecha'], name='agenda_disp_veterin_569b59_idx'),
        ),
        migrations.AddIndex(
            model_name='disponibilidadveterinario',
            index=models.Index(fields=['fecha', 'tipo'], name='agenda_disp_fecha_8fb56b_idx'),
        ),
        migrations.AddIndex(
            model_name='horariofijoveterinario',
            index=models.Index(fields=['veterinario', 'dia_semana'], name='agenda_hora_veterin_9ccaad_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='horariofijoveterinario',
            unique_together={('veterinario', 'dia_semana', 'hora_inicio')},
        ),
    ]
