# Generated by Django 5.2.7 on 2025-11-17 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cita',
            name='tipo',
            field=models.CharField(choices=[('consulta', 'Consulta general'), ('vacunacion', 'Vacunación'), ('control', 'Control'), ('procedimiento', 'Procedimiento')], max_length=30),
        ),
    ]
