# Generated by Django 5.2.7 on 2025-12-09 03:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0002_alter_cita_tipo'),
        ('pacientes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cita',
            options={'ordering': ['fecha', 'hora_inicio'], 'verbose_name': 'Cita', 'verbose_name_plural': 'Citas'},
        ),
        migrations.RenameField(
            model_name='cita',
            old_name='creado',
            new_name='fecha_creacion',
        ),
        migrations.RenameField(
            model_name='cita',
            old_name='hora',
            new_name='hora_inicio',
        ),
        migrations.AlterUniqueTogether(
            name='cita',
            unique_together={('veterinario', 'fecha', 'hora_inicio')},
        ),
        migrations.AddField(
            model_name='cita',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('confirmada', 'Confirmada'), ('en_curso', 'En Curso'), ('completada', 'Completada'), ('cancelada', 'Cancelada'), ('no_asistio', 'No Asistió')], default='pendiente', max_length=20),
        ),
        migrations.AddField(
            model_name='cita',
            name='fecha_modificacion',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='cita',
            name='hora_fin',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cita',
            name='motivo',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cita',
            name='paciente',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='citas', to='pacientes.paciente'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cita',
            name='recordatorio_enviado',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='cita',
            name='tipo',
            field=models.CharField(choices=[('consulta', 'Consulta General'), ('vacunacion', 'Vacunación'), ('cirugia', 'Cirugía'), ('control', 'Control'), ('emergencia', 'Emergencia'), ('peluqueria', 'Peluquería'), ('otro', 'Otro')], default='consulta', max_length=20),
        ),
        migrations.AlterField(
            model_name='cita',
            name='veterinario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='citas_asignadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='cita',
            name='duracion',
        ),
        migrations.RemoveField(
            model_name='cita',
            name='mascota',
        ),
    ]
