# Generated by Django 5.2.7 on 2025-12-12 10:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0003_alter_cita_options_rename_creado_cita_fecha_creacion_and_more'),
        ('pacientes', '0004_remove_paciente_observaciones'),
        ('servicios', '0005_alter_servicioinsumo_unique_together_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DisponibilidadVeterinario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField()),
                ('tipo', models.CharField(choices=[('disponible', 'Disponible'), ('vacaciones', 'Vacaciones'), ('licencia', 'Licencia'), ('ausencia', 'Ausencia')], default='disponible', max_length=20)),
                ('notas', models.TextField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Disponibilidad de Veterinario',
                'verbose_name_plural': 'Disponibilidades de Veterinarios',
                'ordering': ['fecha', 'hora_inicio'],
            },
        ),
        migrations.AddField(
            model_name='cita',
            name='servicio',
            field=models.ForeignKey(blank=True, help_text='Servicio asociado a la cita', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='citas', to='servicios.servicio'),
        ),
        migrations.AlterField(
            model_name='cita',
            name='veterinario',
            field=models.ForeignKey(limit_choices_to={'rol': 'veterinario'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='citas_asignadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='cita',
            index=models.Index(fields=['fecha', 'estado'], name='agenda_cita_fecha_86b79d_idx'),
        ),
        migrations.AddIndex(
            model_name='cita',
            index=models.Index(fields=['veterinario', 'fecha'], name='agenda_cita_veterin_4389cc_idx'),
        ),
        migrations.AddField(
            model_name='disponibilidadveterinario',
            name='veterinario',
            field=models.ForeignKey(limit_choices_to={'rol': 'veterinario'}, on_delete=django.db.models.deletion.CASCADE, related_name='disponibilidades', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='disponibilidadveterinario',
            index=models.Index(fields=['veterinario', 'fecha'], name='agenda_disp_veterin_569b59_idx'),
        ),
        migrations.AddIndex(
            model_name='disponibilidadveterinario',
            index=models.Index(fields=['fecha', 'tipo'], name='agenda_disp_fecha_8fb56b_idx'),
        ),
    ]
