# Generated by Django 5.2.7 on 2025-12-12 11:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0004_disponibilidadveterinario_cita_servicio_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='disponibilidadveterinario',
            options={'ordering': ['fecha', 'hora_inicio'], 'verbose_name': 'Excepción de Disponibilidad', 'verbose_name_plural': 'Excepciones de Disponibilidad'},
        ),
        migrations.AlterField(
            model_name='disponibilidadveterinario',
            name='tipo',
            field=models.CharField(choices=[('vacaciones', 'Vacaciones'), ('licencia', 'Licencia'), ('ausencia', 'Ausencia'), ('disponible_extra', 'Disponibilidad Extra')], default='vacaciones', max_length=20),
        ),
        migrations.CreateModel(
            name='HorarioFijoVeterinario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia_semana', models.IntegerField(choices=[(0, 'Lunes'), (1, 'Martes'), (2, 'Miércoles'), (3, 'Jueves'), (4, 'Viernes'), (5, 'Sábado'), (6, 'Domingo')])),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField()),
                ('activo', models.BooleanField(default=True)),
                ('notas', models.TextField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('veterinario', models.ForeignKey(limit_choices_to={'rol': 'veterinario'}, on_delete=django.db.models.deletion.CASCADE, related_name='horarios_fijos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Horario Fijo de Veterinario',
                'verbose_name_plural': 'Horarios Fijos de Veterinarios',
                'ordering': ['veterinario', 'dia_semana', 'hora_inicio'],
                'indexes': [models.Index(fields=['veterinario', 'dia_semana'], name='agenda_hora_veterin_9ccaad_idx')],
                'unique_together': {('veterinario', 'dia_semana', 'hora_inicio')},
            },
        ),
    ]
