# Generated by Django 5.2.7 on 2025-12-12 22:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0005_alter_disponibilidadveterinario_options_and_more'),
        ('pacientes', '0004_remove_paciente_observaciones'),
        ('servicios', '0006_alter_servicioinsumo_insumo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DisponibilidadBloquesDia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('trabaja', models.BooleanField(default=True)),
                ('rangos', models.JSONField(default=list, help_text='Lista de dicts {"start_block": int, "end_block": int}')),
                ('notas', models.TextField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Disponibilidad diaria (bloques)',
                'verbose_name_plural': 'Disponibilidades diarias (bloques)',
                'ordering': ['fecha'],
            },
        ),
        migrations.AddField(
            model_name='cita',
            name='end_block',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Índice de bloque fin exclusivo (1-96)', null=True),
        ),
        migrations.AddField(
            model_name='cita',
            name='start_block',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Índice de bloque de inicio (0-95)', null=True),
        ),
        migrations.AddIndex(
            model_name='cita',
            index=models.Index(fields=['veterinario', 'fecha', 'start_block'], name='agenda_cita_veterin_b68f08_idx'),
        ),
        migrations.AddField(
            model_name='disponibilidadbloquesdia',
            name='veterinario',
            field=models.ForeignKey(limit_choices_to={'rol': 'veterinario'}, on_delete=django.db.models.deletion.CASCADE, related_name='disponibilidades_bloques', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='disponibilidadbloquesdia',
            index=models.Index(fields=['veterinario', 'fecha'], name='agenda_disp_veterin_cfb6df_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='disponibilidadbloquesdia',
            unique_together={('veterinario', 'fecha')},
        ),
    ]
