# Generated by Django 6.0 on 2025-12-17 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='especie',
            field=models.CharField(choices=[('canino', 'Canino'), ('felino', 'Felino'), ('otro', 'Otro')], max_length=20),
        ),
    ]
