# Generated by Django 6.0 on 2025-12-17 11:44

from django.db import migrations


def actualizar_especies_pacientes(apps, schema_editor):
    """Actualizar valores de especie de perro/gato a canino/felino"""
    Paciente = apps.get_model('pacientes', 'Paciente')
    
    # Actualizar perro -> canino
    Paciente.objects.filter(especie='perro').update(especie='canino')
    
    # Actualizar gato -> felino
    Paciente.objects.filter(especie='gato').update(especie='felino')
    
    print("✅ Especies de pacientes actualizadas: perro→canino, gato→felino")


def revertir_especies_pacientes(apps, schema_editor):
    """Revertir valores de especie de canino/felino a perro/gato"""
    Paciente = apps.get_model('pacientes', 'Paciente')
    
    # Revertir canino -> perro
    Paciente.objects.filter(especie='canino').update(especie='perro')
    
    # Revertir felino -> gato
    Paciente.objects.filter(especie='felino').update(especie='gato')
    
    print("✅ Especies de pacientes revertidas: canino→perro, felino→gato")


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0002_alter_paciente_especie'),
    ]

    operations = [
        migrations.RunPython(actualizar_especies_pacientes, revertir_especies_pacientes),
    ]
