# Generated by Django 5.2.7 on 2025-12-11 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0002_remove_paciente_fecha_ultima_modificacion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='alergias',
            field=models.TextField(blank=True, help_text='Ej: alergia al pollo, penicilina', null=True),
        ),
        migrations.AddField(
            model_name='paciente',
            name='cirugia_previa',
            field=models.TextField(blank=True, help_text='Cirugías previas realizadas', null=True),
        ),
        migrations.AddField(
            model_name='paciente',
            name='enfermedades_cronicas',
            field=models.TextField(blank=True, help_text='Ej: diabetes, artritis', null=True),
        ),
        migrations.AddField(
            model_name='paciente',
            name='medicamentos_actuales',
            field=models.TextField(blank=True, help_text='Medicamentos que está tomando actualmente', null=True),
        ),
    ]
