# Generated by Django 6.0 on 2025-12-17 12:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0003_actualizar_especies_a_canino_felino'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='tipo_ultimo_movimiento',
            field=models.CharField(blank=True, help_text='Tipo del último cambio registrado', max_length=50, null=True, verbose_name='Tipo de Último Movimiento'),
        ),
        migrations.AddField(
            model_name='paciente',
            name='ultimo_movimiento',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Último Movimiento'),
        ),
        migrations.AddField(
            model_name='paciente',
            name='usuario_ultima_modificacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pacientes_modificados', to=settings.AUTH_USER_MODEL, verbose_name='Usuario Última Modificación'),
        ),
    ]
