# Generated by Django 5.2.7 on 2025-12-11 20:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0003_paciente_alergias_paciente_cirugia_previa_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paciente',
            name='observaciones',
        ),
    ]
