# Generated by Django 6.0 on 2025-12-19 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0004_paciente_tipo_ultimo_movimiento_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='microchip',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
