# Generated by Django 5.2.7 on 2025-12-09 03:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventario', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('idServicio', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=150, verbose_name='Nombre del Servicio')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('categoria', models.CharField(max_length=100, verbose_name='Categoría')),
                ('precio', models.PositiveIntegerField(default=0, verbose_name='Precio del Servicio')),
                ('duracion', models.PositiveIntegerField(default=0, verbose_name='Duración (minutos)')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Registro')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Última Actualización')),
            ],
            options={
                'verbose_name': 'Servicio Veterinario',
                'verbose_name_plural': 'Servicios Veterinarios',
                'db_table': 'Servicio',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='ServicioInsumo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField(default=1, verbose_name='Cantidad')),
                ('insumo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='servicios_insumo', to='inventario.insumo')),
                ('servicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='insumos_servicio', to='servicios.servicio')),
            ],
            options={
                'verbose_name': 'Insumo del Servicio',
                'verbose_name_plural': 'Insumos de los Servicios',
                'db_table': 'ServicioInsumo',
                'unique_together': {('servicio', 'insumo')},
            },
        ),
    ]
