# Generated by Django 5.2.7 on 2025-12-09 04:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='servicioinsumo',
            options={'managed': False},
        ),
    ]
