# Generated by Django 5.2.7 on 2025-12-09 06:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0002_alter_servicioinsumo_options'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='servicioinsumo',
            table='servicio_insumo',
        ),
    ]
