# Generated by Django 5.2.7 on 2025-12-11 07:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0003_alter_servicioinsumo_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='servicioinsumo',
            options={},
        ),
    ]
