# Generated by Django 5.2.7 on 2025-12-12 08:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0006_insumo_cantidad_pastillas_insumo_formato_and_more'),
        ('servicios', '0004_alter_servicioinsumo_options'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='servicioinsumo',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='servicioinsumo',
            name='cantidad',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='servicioinsumo',
            name='insumo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.insumo'),
        ),
        migrations.AlterField(
            model_name='servicioinsumo',
            name='servicio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='servicios.servicio'),
        ),
    ]
