# Generated by Django 5.2.7 on 2025-12-12 10:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0006_insumo_cantidad_pastillas_insumo_formato_and_more'),
        ('servicios', '0005_alter_servicioinsumo_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicioinsumo',
            name='insumo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventario.insumo'),
        ),
    ]
