# Generated by Django 5.2.7 on 2025-11-08 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuentas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='rol',
            field=models.CharField(choices=[('administracion', 'Administración'), ('veterinario', 'Veterinario'), ('recepcion', 'Recepción')], default='recepcion', max_length=20, verbose_name='Rol'),
        ),
    ]
