# Generated by Django 5.2.7 on 2025-12-08 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuentas', '0002_customuser_rol'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='username',
            field=models.CharField(default='temp', editable=False, max_length=20, unique=True),
            preserve_default=False,
        ),
    ]
