# Generated by Django 6.0 on 2025-12-18 20:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('reportes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReporteGenerado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('inventario', 'Inventario'), ('caja', 'Caja'), ('clinica', 'Clínica'), ('hospitalizacion', 'Hospitalización'), ('servicios', 'Servicios')], max_length=20)),
                ('fecha_generacion', models.DateTimeField(auto_now_add=True)),
                ('filtros', models.JSONField(blank=True, default=dict)),
                ('archivo', models.FileField(blank=True, null=True, upload_to='reportes/excel/')),
                ('total_registros', models.IntegerField(default=0)),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Reporte Generado',
                'verbose_name_plural': 'Reportes Generados',
                'ordering': ['-fecha_generacion'],
            },
        ),
    ]
