# Generated by Django 6.0 on 2025-12-18 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reportes', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportegenerado',
            name='observaciones',
            field=models.TextField(blank=True, help_text='Información adicional sobre el reporte', null=True),
        ),
        migrations.AddField(
            model_name='reportegenerado',
            name='resumen_filtros',
            field=models.TextField(blank=True, help_text='Resumen legible de los filtros aplicados'),
        ),
    ]
