# Generated by Django 6.0 on 2025-12-14 13:28

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_alta', models.DateTimeField()),
                ('diagnostico_final', models.TextField(blank=True)),
                ('tratamiento_post_alta', models.TextField(blank=True)),
                ('recomendaciones', models.TextField(blank=True)),
                ('proxima_revision', models.DateField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Alta Médica',
                'verbose_name_plural': 'Altas Médicas',
            },
        ),
        migrations.CreateModel(
            name='Cirugia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_cirugia', models.DateTimeField()),
                ('tipo_cirugia', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
                ('duracion_minutos', models.IntegerField(blank=True, null=True)),
                ('anestesiologo', models.CharField(blank=True, max_length=100)),
                ('tipo_anestesia', models.CharField(blank=True, max_length=100)),
                ('complicaciones', models.TextField(blank=True)),
                ('resultado', models.CharField(blank=True, choices=[('', 'Sin resultado'), ('exitosa', 'Exitosa'), ('con_complicaciones', 'Con complicaciones'), ('problemas', 'Problemas')], default='', max_length=25)),
            ],
            options={
                'verbose_name': 'Cirugía',
                'verbose_name_plural': 'Cirugías',
                'ordering': ['-fecha_cirugia'],
            },
        ),
        migrations.CreateModel(
            name='CirugiaInsumo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('peso_paciente', models.DecimalField(decimal_places=2, max_digits=6)),
                ('dosis_ml_por_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('dosis_total_ml', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('ml_por_contenedor', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('cantidad_calculada', models.DecimalField(decimal_places=2, default=1, max_digits=10)),
                ('cantidad_manual', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('cantidad_final', models.DecimalField(decimal_places=2, default=1, max_digits=10)),
                ('calculo_automatico', models.BooleanField(default=False)),
                ('requiere_confirmacion', models.BooleanField(default=False)),
                ('fecha_confirmacion', models.DateTimeField(blank=True, null=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Insumo de Cirugía',
                'verbose_name_plural': 'Insumos de Cirugía',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Consulta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now)),
                ('tipo_consulta', models.CharField(choices=[('consulta_general', 'Consulta general'), ('urgencia', 'Urgencia'), ('vacuna', 'Vacuna'), ('desparacitacion', 'Desparacitación'), ('control', 'Control'), ('cirugia', 'Cirugía'), ('otros', 'Otros')], default='consulta_general', max_length=30)),
                ('temperatura', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('peso', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('frecuencia_cardiaca', models.IntegerField(blank=True, null=True)),
                ('frecuencia_respiratoria', models.IntegerField(blank=True, null=True)),
                ('otros', models.TextField(blank=True, null=True)),
                ('diagnostico', models.TextField()),
                ('tratamiento', models.TextField(blank=True)),
                ('notas', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Consulta',
                'verbose_name_plural': 'Consultas',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='ConsultaInsumo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('peso_paciente', models.DecimalField(decimal_places=2, max_digits=6)),
                ('dosis_ml_por_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('dosis_total_ml', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('ml_por_contenedor', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('cantidad_calculada', models.DecimalField(decimal_places=2, default=1, max_digits=10)),
                ('cantidad_manual', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('cantidad_final', models.DecimalField(decimal_places=2, default=1, max_digits=10)),
                ('calculo_automatico', models.BooleanField(default=False)),
                ('requiere_confirmacion', models.BooleanField(default=False, help_text='Faltan datos para cálculo automático')),
                ('fecha_confirmacion', models.DateTimeField(blank=True, null=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Insumo de Consulta',
                'verbose_name_plural': 'Insumos de Consulta',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('archivo', models.FileField(upload_to='documentos/')),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Documento',
                'verbose_name_plural': 'Documentos',
                'ordering': ['-fecha_subida'],
            },
        ),
        migrations.CreateModel(
            name='Examen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('tipo', models.CharField(max_length=100)),
                ('resultado', models.TextField(blank=True, null=True)),
                ('archivo', models.FileField(blank=True, null=True, upload_to='examenes/')),
            ],
            options={
                'verbose_name': 'Examen',
                'verbose_name_plural': 'Exámenes',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='Hospitalizacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_ingreso', models.DateTimeField()),
                ('fecha_alta', models.DateTimeField(blank=True, null=True)),
                ('motivo', models.TextField()),
                ('diagnostico_hosp', models.TextField(blank=True)),
                ('estado', models.CharField(choices=[('activa', 'Activa'), ('alta', 'Alta'), ('fallecido', 'Fallecido')], default='activa', max_length=20)),
                ('observaciones', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Hospitalización',
                'verbose_name_plural': 'Hospitalizaciones',
                'ordering': ['-fecha_ingreso'],
            },
        ),
        migrations.CreateModel(
            name='HospitalizacionInsumo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('peso_paciente', models.DecimalField(decimal_places=2, max_digits=6)),
                ('dosis_ml_por_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('dosis_total_ml', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('ml_por_contenedor', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('cantidad_calculada', models.DecimalField(decimal_places=2, default=1, max_digits=10)),
                ('cantidad_manual', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('cantidad_final', models.DecimalField(decimal_places=2, default=1, max_digits=10)),
                ('calculo_automatico', models.BooleanField(default=False)),
                ('requiere_confirmacion', models.BooleanField(default=False)),
                ('fecha_confirmacion', models.DateTimeField(blank=True, null=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Insumo de Hospitalización',
                'verbose_name_plural': 'Insumos de Hospitalización',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='MedicamentoUtilizado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inventario_id', models.IntegerField(blank=True, help_text='ID del producto de inventario', null=True)),
                ('nombre', models.CharField(max_length=200)),
                ('dosis', models.CharField(blank=True, max_length=100, null=True)),
                ('peso_paciente', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Medicamento Utilizado',
                'verbose_name_plural': 'Medicamentos Utilizados',
            },
        ),
        migrations.CreateModel(
            name='RegistroDiario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_registro', models.DateTimeField()),
                ('temperatura', models.DecimalField(decimal_places=1, max_digits=4)),
                ('peso', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('frecuencia_cardiaca', models.IntegerField(blank=True, null=True)),
                ('frecuencia_respiratoria', models.IntegerField(blank=True, null=True)),
                ('observaciones', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Registro Diario',
                'verbose_name_plural': 'Registros Diarios',
                'ordering': ['-fecha_registro'],
            },
        ),
    ]
