# Generated by Django 6.0 on 2025-12-14 13:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clinica', '0001_initial'),
        ('inventario', '0001_initial'),
        ('pacientes', '0001_initial'),
        ('servicios', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='cirugia',
            name='medicamentos',
            field=models.ManyToManyField(blank=True, related_name='cirugias_usadas', to='inventario.insumo'),
        ),
        migrations.AddField(
            model_name='cirugia',
            name='servicio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cirugias', to='servicios.servicio'),
        ),
        migrations.AddField(
            model_name='cirugia',
            name='veterinario_cirujano',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cirugias_realizadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cirugiainsumo',
            name='cirugia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='insumos_detalle', to='clinica.cirugia'),
        ),
        migrations.AddField(
            model_name='cirugiainsumo',
            name='confirmado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='insumos_cirugia_confirmados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cirugiainsumo',
            name='insumo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventario.insumo'),
        ),
        migrations.AddField(
            model_name='consulta',
            name='medicamentos',
            field=models.ManyToManyField(blank=True, related_name='consultas_usadas', to='inventario.insumo'),
        ),
        migrations.AddField(
            model_name='consulta',
            name='paciente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consultas', to='pacientes.paciente'),
        ),
        migrations.AddField(
            model_name='consulta',
            name='servicios',
            field=models.ManyToManyField(blank=True, related_name='consultas', to='servicios.servicio'),
        ),
        migrations.AddField(
            model_name='consulta',
            name='veterinario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='consultainsumo',
            name='confirmado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='insumos_consulta_confirmados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='consultainsumo',
            name='consulta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='insumos_detalle', to='clinica.consulta'),
        ),
        migrations.AddField(
            model_name='consultainsumo',
            name='insumo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventario.insumo'),
        ),
        migrations.AddField(
            model_name='documento',
            name='paciente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='pacientes.paciente'),
        ),
        migrations.AddField(
            model_name='examen',
            name='paciente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='examenes', to='pacientes.paciente'),
        ),
        migrations.AddField(
            model_name='examen',
            name='veterinario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='hospitalizacion',
            name='insumos',
            field=models.ManyToManyField(blank=True, related_name='hospitalizaciones_usadas', to='inventario.insumo'),
        ),
        migrations.AddField(
            model_name='hospitalizacion',
            name='paciente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hospitalizaciones', to='pacientes.paciente'),
        ),
        migrations.AddField(
            model_name='hospitalizacion',
            name='veterinario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hospitalizaciones_atendidas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cirugia',
            name='hospitalizacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cirugias', to='clinica.hospitalizacion'),
        ),
        migrations.AddField(
            model_name='alta',
            name='hospitalizacion',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='alta_medica', to='clinica.hospitalizacion'),
        ),
        migrations.AddField(
            model_name='hospitalizacioninsumo',
            name='confirmado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='insumos_hosp_confirmados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='hospitalizacioninsumo',
            name='hospitalizacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='insumos_detalle', to='clinica.hospitalizacion'),
        ),
        migrations.AddField(
            model_name='hospitalizacioninsumo',
            name='insumo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventario.insumo'),
        ),
        migrations.AddField(
            model_name='medicamentoutilizado',
            name='consulta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medicamentos_detalle', to='clinica.consulta'),
        ),
        migrations.AddField(
            model_name='registrodiario',
            name='hospitalizacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registros_diarios', to='clinica.hospitalizacion'),
        ),
        migrations.AddField(
            model_name='registrodiario',
            name='medicamentos',
            field=models.ManyToManyField(blank=True, related_name='registros_usados', to='inventario.insumo'),
        ),
    ]
