# Generated by Django 5.2.7 on 2025-12-09 07:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinica', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('especie', models.CharField(choices=[('perro', 'Perro'), ('gato', 'Gato'), ('otro', 'Otro')], max_length=20)),
                ('raza', models.CharField(blank=True, max_length=100, null=True)),
                ('color', models.CharField(blank=True, max_length=50, null=True)),
                ('sexo', models.CharField(choices=[('M', 'Macho'), ('H', 'Hembra')], max_length=1)),
                ('fecha_nacimiento', models.DateField(blank=True, null=True)),
                ('edad', models.IntegerField(blank=True, help_text='Años estimados', null=True)),
                ('edad_meses', models.IntegerField(blank=True, help_text='Meses adicionales', null=True)),
                ('microchip', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Paciente',
                'verbose_name_plural': 'Pacientes',
                'ordering': ['-fecha_registro'],
            },
        ),
        migrations.CreateModel(
            name='Propietario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('direccion', models.TextField(blank=True, null=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Propietario',
                'verbose_name_plural': 'Propietarios',
                'ordering': ['apellido', 'nombre'],
            },
        ),
        migrations.RenameField(
            model_name='consulta',
            old_name='examenes',
            new_name='otros',
        ),
        migrations.RemoveField(
            model_name='consulta',
            name='motivo_consulta',
        ),
        migrations.RemoveField(
            model_name='consulta',
            name='otros_signos',
        ),
        migrations.RemoveField(
            model_name='consulta',
            name='proxima_cita',
        ),
        migrations.RemoveField(
            model_name='consulta',
            name='recomendaciones',
        ),
        migrations.AlterField(
            model_name='consulta',
            name='frecuencia_cardiaca',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='consulta',
            name='frecuencia_respiratoria',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='consulta',
            name='peso',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='consulta',
            name='temperatura',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='examen',
            name='fecha',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='examen',
            name='resultado',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='examen',
            name='tipo',
            field=models.CharField(max_length=100),
        ),
        migrations.CreateModel(
            name='MedicamentoUtilizado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inventario_id', models.IntegerField(blank=True, help_text='ID del producto de inventario', null=True)),
                ('nombre', models.CharField(max_length=200)),
                ('dosis', models.CharField(blank=True, max_length=100, null=True)),
                ('peso_paciente', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('consulta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medicamentos', to='clinica.consulta')),
            ],
            options={
                'verbose_name': 'Medicamento Utilizado',
                'verbose_name_plural': 'Medicamentos Utilizados',
            },
        ),
        migrations.CreateModel(
            name='Hospitalizacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_ingreso', models.DateTimeField()),
                ('fecha_alta', models.DateTimeField(blank=True, null=True)),
                ('motivo', models.TextField()),
                ('estado', models.CharField(choices=[('activa', 'Activa'), ('alta', 'Alta'), ('fallecido', 'Fallecido')], default='activa', max_length=20)),
                ('notas', models.TextField(blank=True, null=True)),
                ('veterinario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hospitalizaciones_atendidas', to=settings.AUTH_USER_MODEL)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hospitalizaciones', to='clinica.paciente')),
            ],
            options={
                'verbose_name': 'Hospitalización',
                'verbose_name_plural': 'Hospitalizaciones',
                'ordering': ['-fecha_ingreso'],
            },
        ),
        migrations.AlterField(
            model_name='consulta',
            name='paciente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consultas', to='clinica.paciente'),
        ),
        migrations.AlterField(
            model_name='documento',
            name='paciente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='clinica.paciente'),
        ),
        migrations.AlterField(
            model_name='examen',
            name='paciente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='examenes', to='clinica.paciente'),
        ),
        migrations.AddField(
            model_name='paciente',
            name='propietario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mascotas', to='clinica.propietario'),
        ),
    ]
