# Generated by Django 5.2.7 on 2025-12-09 08:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinica', '0002_paciente_propietario_rename_examenes_consulta_otros_and_more'),
        ('pacientes', '0002_remove_paciente_fecha_ultima_modificacion_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paciente',
            name='propietario',
        ),
        migrations.AlterField(
            model_name='consulta',
            name='paciente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consultas', to='pacientes.paciente'),
        ),
        migrations.AlterField(
            model_name='hospitalizacion',
            name='paciente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hospitalizaciones', to='pacientes.paciente'),
        ),
        migrations.AlterField(
            model_name='examen',
            name='paciente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='examenes', to='pacientes.paciente'),
        ),
        migrations.AlterField(
            model_name='documento',
            name='paciente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='pacientes.paciente'),
        ),
        migrations.DeleteModel(
            name='Propietario',
        ),
        migrations.DeleteModel(
            name='Paciente',
        ),
    ]
