# Generated by Django 6.0 on 2025-12-15 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinica', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='consulta',
            name='insumos_descontados',
            field=models.BooleanField(default=False, help_text='Indica si los insumos de esta consulta ya fueron descontados del inventario. Previene descuentos duplicados.'),
        ),
        migrations.AddField(
            model_name='hospitalizacion',
            name='insumos_descontados',
            field=models.BooleanField(default=False, help_text='Indica si los insumos de esta hospitalización ya fueron descontados del inventario. Previene descuentos duplicados.'),
        ),
    ]
