# Generated by Django 6.0 on 2025-12-16 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinica', '0003_consulta_insumos_descontados_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultainsumo',
            name='fecha_descuento',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='consultainsumo',
            name='stock_descontado',
            field=models.BooleanField(default=False, help_text='Indica si el stock de este insumo ya fue descontado. Previene descuentos duplicados.'),
        ),
        migrations.AddField(
            model_name='hospitalizacioninsumo',
            name='fecha_descuento',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hospitalizacioninsumo',
            name='stock_descontado',
            field=models.BooleanField(default=False, help_text='Indica si el stock de este insumo ya fue descontado. Previene descuentos duplicados.'),
        ),
    ]
