# Generated by Django 5.2.7 on 2025-12-09 18:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinica', '0003_remove_paciente_propietario_alter_consulta_paciente_and_more'),
        ('inventario', '0006_insumo_cantidad_pastillas_insumo_formato_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='consulta',
            name='medicamentos',
            field=models.ManyToManyField(blank=True, related_name='consultas_usadas', to='inventario.insumo'),
        ),
        migrations.AlterField(
            model_name='consulta',
            name='diagnostico',
            field=models.TextField(blank=True, default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='consulta',
            name='frecuencia_cardiaca',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='consulta',
            name='frecuencia_respiratoria',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='consulta',
            name='notas',
            field=models.TextField(blank=True, default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='consulta',
            name='otros',
            field=models.TextField(blank=True, default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='consulta',
            name='temperatura',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True),
        ),
        migrations.AlterField(
            model_name='consulta',
            name='tratamiento',
            field=models.TextField(blank=True, default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='consulta',
            name='veterinario',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='medicamentoutilizado',
            name='consulta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medicamentos_detalle', to='clinica.consulta'),
        ),
    ]
