# Generated by manual creation for VetSantaSofia

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clinica', '0008_documento'),
        ('servicios', '0001_initial'),
    ]

    operations = [
        # 1. Eliminar el campo veterinario de RegistroDiario (si existe)
        migrations.RemoveField(
            model_name='registrodiario',
            name='veterinario',
        ),
        
        # 2. Cambiar Cirugia.hospitalizacion de OneToOneField a ForeignKey
        migrations.AlterField(
            model_name='cirugia',
            name='hospitalizacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cirugias', to='clinica.hospitalizacion'),
        ),
        
        # 3. Agregar campo servicio a Cirugia
        migrations.AddField(
            model_name='cirugia',
            name='servicio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cirugias', to='servicios.servicio'),
        ),
        
        # 4. Actualizar los choices de resultado en Cirugia
        migrations.AlterField(
            model_name='cirugia',
            name='resultado',
            field=models.CharField(blank=True, choices=[('', 'Sin resultado'), ('exitosa', 'Exitosa'), ('con_complicaciones', 'Con complicaciones'), ('problemas', 'Problemas')], default='', max_length=25),
        ),
        
        # 5. Hacer temperatura obligatoria en RegistroDiario
        # Primero actualizar valores NULL existentes con un valor por defecto
        migrations.RunSQL(
            "UPDATE clinica_registrodiario SET temperatura = 37.5 WHERE temperatura IS NULL;",
            reverse_sql="SELECT 1;",  # No-op en reversa
        ),
        # Luego cambiar el campo a NOT NULL
        migrations.AlterField(
            model_name='registrodiario',
            name='temperatura',
            field=models.DecimalField(decimal_places=1, max_digits=4),
        ),
        
        # 6. Hacer campos de Alta opcionales
        migrations.AlterField(
            model_name='alta',
            name='diagnostico_final',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='alta',
            name='tratamiento_post_alta',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='alta',
            name='recomendaciones',
            field=models.TextField(blank=True),
        ),
    ]
