# Generated by Django 5.2.7 on 2025-12-12 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinica', '0009_consolidate_models'),
        ('inventario', '0006_insumo_cantidad_pastillas_insumo_formato_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospitalizacion',
            name='insumos',
            field=models.ManyToManyField(blank=True, related_name='hospitalizaciones_usadas', to='inventario.insumo'),
        ),
    ]
