# Generated by Django 5.2.7 on 2025-12-12 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinica', '0010_hospitalizacion_insumos'),
        ('servicios', '0004_alter_servicioinsumo_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='consulta',
            name='servicios',
            field=models.ManyToManyField(blank=True, related_name='consultas', to='servicios.servicio'),
        ),
    ]
