# Generated by Django 5.2.7 on 2025-12-12 11:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinica', '0011_consulta_servicios'),
        ('inventario', '0006_insumo_cantidad_pastillas_insumo_formato_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CirugiaInsumo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('peso_paciente', models.DecimalField(decimal_places=2, max_digits=6)),
                ('dosis_ml_por_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('dosis_total_ml', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('ml_por_contenedor', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('cantidad_calculada', models.DecimalField(decimal_places=2, default=1, max_digits=10)),
                ('cantidad_manual', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('cantidad_final', models.DecimalField(decimal_places=2, default=1, max_digits=10)),
                ('calculo_automatico', models.BooleanField(default=False)),
                ('requiere_confirmacion', models.BooleanField(default=False)),
                ('fecha_confirmacion', models.DateTimeField(blank=True, null=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('cirugia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='insumos_detalle', to='clinica.cirugia')),
                ('confirmado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='insumos_cirugia_confirmados', to=settings.AUTH_USER_MODEL)),
                ('insumo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventario.insumo')),
            ],
            options={
                'verbose_name': 'Insumo de Cirugía',
                'verbose_name_plural': 'Insumos de Cirugía',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='ConsultaInsumo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('peso_paciente', models.DecimalField(decimal_places=2, max_digits=6)),
                ('dosis_ml_por_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('dosis_total_ml', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('ml_por_contenedor', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('cantidad_calculada', models.DecimalField(decimal_places=2, default=1, max_digits=10)),
                ('cantidad_manual', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('cantidad_final', models.DecimalField(decimal_places=2, default=1, max_digits=10)),
                ('calculo_automatico', models.BooleanField(default=False)),
                ('requiere_confirmacion', models.BooleanField(default=False, help_text='Faltan datos para cálculo automático')),
                ('fecha_confirmacion', models.DateTimeField(blank=True, null=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('confirmado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='insumos_consulta_confirmados', to=settings.AUTH_USER_MODEL)),
                ('consulta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='insumos_detalle', to='clinica.consulta')),
                ('insumo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventario.insumo')),
            ],
            options={
                'verbose_name': 'Insumo de Consulta',
                'verbose_name_plural': 'Insumos de Consulta',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='HospitalizacionInsumo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('peso_paciente', models.DecimalField(decimal_places=2, max_digits=6)),
                ('dosis_ml_por_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('dosis_total_ml', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('ml_por_contenedor', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('cantidad_calculada', models.DecimalField(decimal_places=2, default=1, max_digits=10)),
                ('cantidad_manual', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('cantidad_final', models.DecimalField(decimal_places=2, default=1, max_digits=10)),
                ('calculo_automatico', models.BooleanField(default=False)),
                ('requiere_confirmacion', models.BooleanField(default=False)),
                ('fecha_confirmacion', models.DateTimeField(blank=True, null=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('confirmado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='insumos_hosp_confirmados', to=settings.AUTH_USER_MODEL)),
                ('hospitalizacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='insumos_detalle', to='clinica.hospitalizacion')),
                ('insumo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventario.insumo')),
            ],
            options={
                'verbose_name': 'Insumo de Hospitalización',
                'verbose_name_plural': 'Insumos de Hospitalización',
                'ordering': ['id'],
            },
        ),
    ]
