const STORE_KEY='vetsantasofia-demo-v4';
const DEFAULT_DATE='2026-08-17';
let state=loadState(),selectedPatientId=1;
const $=id=>document.getElementById(id);
const cloneSeed=()=>JSON.parse(JSON.stringify(window.VET_DEMO_SEED));
function loadState(){try{const x=JSON.parse(localStorage.getItem(STORE_KEY));return x&&x.vets&&x.services&&x.patients?x:cloneSeed()}catch{return cloneSeed()}}
function save(){localStorage.setItem(STORE_KEY,JSON.stringify(state))}
const patient=id=>state.patients.find(x=>x.id===Number(id));
const vet=id=>state.vets.find(x=>x.id===Number(id));
const service=id=>state.services.find(x=>x.id===Number(id));
const fmt=v=>new Intl.DateTimeFormat('es-CL',{day:'2-digit',month:'short',year:'numeric'}).format(new Date(v.slice(0,10)+'T12:00:00'));
function toast(text){const t=$('toast');t.textContent=text;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),1800)}
function slots(){const r=[];for(let h=9;h<=17;h++)for(const m of [0,30])r.push(`${String(h).padStart(2,'0')}:${String(m).padStart(2,'0')}`);return r}
function addMinutes(time,min){const [h,m]=time.split(':').map(Number);const d=new Date(2000,0,1,h,m+min);return `${String(d.getHours()).padStart(2,'0')}:${String(d.getMinutes()).padStart(2,'0')}`}
function appointmentBlocks(a){const s=service(a.serviceId);const count=Math.ceil((s?.duration||30)/30);const all=slots();const i=all.indexOf(a.time);return i<0?[]:all.slice(i,i+count)}
function go(view){document.querySelectorAll('.view').forEach(x=>x.classList.remove('active-view'));$(view).classList.add('active-view');document.querySelectorAll('.nav-item').forEach(x=>x.classList.toggle('active',x.dataset.view===view));$('viewTitle').textContent={dashboard:'Panel General',agenda:'Agenda Veterinaria',pacientes:'Pacientes',ficha:'Ficha clínica'}[view];$('vetSidebar').classList.remove('open');if(view==='dashboard')renderDashboard();if(view==='agenda')renderAgenda();if(view==='pacientes')renderPatients();if(view==='ficha')renderFicha()}
function renderDashboard(){const apps=state.appointments.filter(a=>a.date===DEFAULT_DATE);$('metricCitas').textContent=apps.length;$('metricPendientes').textContent=apps.filter(a=>a.status!=='completada').length;$('metricPacientes').textContent=state.patients.length;$('metricAtendidos').textContent=apps.filter(a=>a.status==='completada').length;$('upcomingList').innerHTML=apps.sort((a,b)=>a.time.localeCompare(b.time)).map(a=>`<div class="appointment"><time>${a.time}</time><div><strong>${patient(a.patientId).name} · ${service(a.serviceId).name}</strong><small>${vet(a.vetId).name} · ${a.reason}</small></div><span class="badge ${a.status}">${a.status}</span></div>`).join('');const events=Object.entries(state.timeline).flatMap(([id,arr])=>arr.map(e=>({...e,pid:+id}))).sort((a,b)=>b.date.localeCompare(a.date)).slice(0,4);$('recentActivity').innerHTML=events.map(e=>`<div class="mini-event"><strong>${patient(e.pid).name} · ${e.title}</strong><small>${fmt(e.date)} · ${e.vet}</small></div>`).join('')}
function renderAgenda(){const date=$('agendaDate').value||DEFAULT_DATE;const filter=$('vetFilter').value;$('agendaTitle').textContent=`Agenda · ${fmt(date)}`;const vets=filter?state.vets.filter(v=>String(v.id)===filter):state.vets;$('vetAgendas').innerHTML=vets.map(v=>renderVetAgenda(v,date)).join('');document.querySelectorAll('[data-free-slot]').forEach(b=>b.onclick=()=>openBooking({vetId:+b.dataset.vet,time:b.dataset.freeSlot}));}
function renderVetAgenda(v,date){const apps=state.appointments.filter(a=>a.date===date&&a.vetId===v.id);const occupied=new Map();apps.forEach(a=>appointmentBlocks(a).forEach((t,i)=>occupied.set(t,{a,index:i,total:appointmentBlocks(a).length})));const blocks=slots().map(t=>{if(!v.availability.includes(t))return `<div class="agenda-block unavailable"><b>${t}</b><small>No disponible</small></div>`;const hit=occupied.get(t);if(!hit)return `<button class="agenda-block available" data-free-slot="${t}" data-vet="${v.id}"><b>${t}</b><span>Disponible</span></button>`;const a=hit.a,s=service(a.serviceId),p=patient(a.patientId);return `<div class="agenda-block occupied ${s.category==='Cirugía'?'surgery':''}"><b>${t}</b><span>${p.name}</span><small>${s.name}${hit.total>1?` · bloque ${hit.index+1}/${hit.total}`:''}</small></div>`}).join('');return `<div class="agenda-vet-col"><div class="section"><div class="vet-agenda-head"><h4><i class="fas fa-user-md"></i> ${v.name}</h4><small>${v.role}</small></div><div class="agenda-bloques-grid demo-block-grid">${blocks}</div></div></div>`}
function renderPatients(q=''){q=q.toLowerCase();const list=state.patients.filter(x=>[x.name,x.species,x.owner,x.breed].some(v=>v.toLowerCase().includes(q)));$('patientRows').innerHTML=list.map(x=>`<tr><td><b>${x.name}</b><br><small>${x.breed}</small></td><td>${x.species}</td><td>${x.owner}</td><td>${x.age}</td><td>${fmt(x.lastVisit)}</td><td><button class="table-link" data-patient="${x.id}">Ver ficha</button></td></tr>`).join('');document.querySelectorAll('[data-patient]').forEach(b=>b.onclick=()=>{selectedPatientId=+b.dataset.patient;go('ficha')})}
function realInfo(rows){return rows.map(([k,v])=>`<div class="info-row"><p><strong>${k}:</strong> ${v||'No registrado'}</p></div>`).join('')}
function renderFicha(){const x=patient(selectedPatientId);$('fichaTitlePatient').textContent=x.name;$('patientSelect').value=x.id;$('generalInfo').innerHTML=realInfo([['Nombre',x.name],['Especie',x.species],['Raza',x.breed],['Color',x.color],['Sexo',x.sex],['Edad',x.age],['Microchip',x.microchip]]);$('ownerInfo').innerHTML=realInfo([['Dueño',x.owner],['Teléfono',x.phone],['Correo Electrónico',x.email],['Dirección',x.address]]);$('criticalInfo').innerHTML=realInfo([['Alergias',x.allergies],['Enfermedades Crónicas',x.chronic],['Medicamentos Actuales',x.medications],['Cirugías Previas',x.surgeries]]);const hs=state.hospitalizations[x.id]||[];$('clinicalSummary').innerHTML=realInfo([['Último peso registrado',x.weight],['Último control',fmt(x.lastVisit)],['Consultas registradas',(state.timeline[x.id]||[]).length],['Hospitalizaciones',hs.length]]);const active=hs.find(h=>h.status==='activa');$('activeHospBanner').classList.toggle('d-none',!active);if(active)$('activeHospText').textContent=`Ingreso ${fmt(active.admission)} · ${active.reason}`;renderTimeline();renderHospitalizations();renderDocuments();renderAudit();renderInventory()}
function renderTimeline(){const q=$('historySearch').value.toLowerCase();const items=(state.timeline[selectedPatientId]||[]).filter(e=>JSON.stringify(e).toLowerCase().includes(q)).sort((a,b)=>b.date.localeCompare(a.date));$('historyCount').textContent=`Items: ${items.length}`;$('timeline').innerHTML=items.map(e=>`<div class="real-timeline-item"><div class="timeline-datebox"><b>${new Date(e.date+'T12:00:00').getDate()}</b><span>${new Date(e.date+'T12:00:00').toLocaleString('es',{month:'short'}).toUpperCase()}</span></div><div class="timeline-marker"></div><div class="timeline-card"><h4>${e.title}</h4><div class="timeline-meta">${e.vet} · ${e.type}</div><p>${e.text}</p><small><b>Diagnóstico:</b> ${e.diagnosis||'-'} · <b>Tratamiento:</b> ${e.treatment||'-'}</small></div></div>`).join('')||'<p class="text-muted">Sin registros.</p>'}
function renderHospitalizations(){const hs=state.hospitalizations[selectedPatientId]||[];$('hospitalizationsContainer').innerHTML=hs.map(h=>`<article class="hosp-card"><div class="hosp-head"><div><b>${h.reason}</b><small>${fmt(h.admission)} · ${h.vet}</small></div><span class="badge ${h.status==='activa'?'bg-warning':'bg-success'}">${h.status}</span></div><div class="hosp-body"><p><b>Diagnóstico:</b> ${h.diagnosis}</p><h5>Registros diarios</h5>${(h.daily||[]).map(r=>`<div class="daily-row"><span>${fmt(r.date)} · ${r.temp}°C · FC ${r.hr}</span><span>${r.note}</span></div>`).join('')}<h5 class="mt-3">Cirugías</h5>${(h.surgeries||[]).map(s=>`<p>${s.type} · ${s.duration} min · ${s.result}</p>`).join('')||'<small>Sin cirugías</small>'}${h.status==='activa'?`<button class="btn btn-sm btn-primary mt-2" data-daily="${h.id}">+ Registro diario</button> <button class="btn btn-sm btn-success mt-2" data-discharge="${h.id}">Dar alta</button>`:''}</div></article>`).join('')||'<p class="text-muted">No hay hospitalizaciones.</p>';document.querySelectorAll('[data-daily]').forEach(b=>b.onclick=()=>{ $('dailyHospId').value=b.dataset.daily; openDialog('dailyModal')});document.querySelectorAll('[data-discharge]').forEach(b=>b.onclick=()=>discharge(+b.dataset.discharge))}
function renderDocuments(){$('documentsList').innerHTML=(state.documents[selectedPatientId]||[]).map(d=>`<div class="doc-row"><b>${d.name}</b><span>${fmt(d.date)}</span></div>`).join('')||'<p class="text-muted">Sin documentos.</p>'}
function renderAudit(){$('auditList').innerHTML=(state.audit[selectedPatientId]||[]).map(a=>`<div class="audit-row"><b>${a.event}</b><span>${a.user} · ${a.date}</span></div>`).join('')||'<p class="text-muted">Sin registros.</p>'}
function renderInventory(){const html=state.inventory.map(i=>`<label class="inventory-select-row"><input type="checkbox" value="${i.id}"><span>${i.name}</span><small>Stock ${i.stock}</small></label>`).join('');$('consultInventory').innerHTML=html;$('hospitalInventory').innerHTML=html}
function populate(){const ps=state.patients.map(p=>`<option value="${p.id}">${p.name} · ${p.owner}</option>`).join('');$('patientSelect').innerHTML=ps;$('bookingPatient').innerHTML=ps;$('vetFilter').innerHTML='<option value="">Todos los veterinarios</option>'+state.vets.map(v=>`<option value="${v.id}">${v.name}</option>`).join('');$('bookingVet').innerHTML=state.vets.map(v=>`<option value="${v.id}">${v.name}</option>`).join('');const services=state.services.map(s=>`<option value="${s.id}" data-duration="${s.duration}">${s.name} (${s.duration} min)</option>`).join('');$('bookingService').innerHTML=services;$('consultService').innerHTML=services}
function openDialog(id){const d=$(id);if(!d.open)d.showModal()}
function closeDialog(d){if(d?.open)d.close()}
function availableStarts(vetId,date,serviceId){const v=vet(vetId),s=service(serviceId),all=slots(),apps=state.appointments.filter(a=>a.date===date&&a.vetId===vetId);const blocked=new Set(apps.flatMap(appointmentBlocks));const need=Math.ceil(s.duration/30);return all.filter((t,i)=>{const req=all.slice(i,i+need);return req.length===need&&req.every(x=>v.availability.includes(x)&&!blocked.has(x))})}
function refreshBookingTimes(){const starts=availableStarts(+$('bookingVet').value,$('bookingDate').value,+$('bookingService').value);$('bookingTime').innerHTML=starts.map(t=>`<option>${t}</option>`).join('');const s=service(+$('bookingService').value);$('bookingBlocks').textContent=`Duración: ${s.duration} min · ${Math.ceil(s.duration/30)} bloque(s) de 30 min`}
function openBooking(pref={}){if(pref.vetId)$('bookingVet').value=pref.vetId;$('bookingDate').value=$('agendaDate').value||DEFAULT_DATE;refreshBookingTimes();if(pref.time)$('bookingTime').value=pref.time;openDialog('bookingModal')}
function saveBooking(e){e.preventDefault();const vetId=+$('bookingVet').value,serviceId=+$('bookingService').value,date=$('bookingDate').value,time=$('bookingTime').value;if(!time)return toast('No hay bloques consecutivos disponibles.');state.appointments.push({id:Date.now(),patientId:+$('bookingPatient').value,vetId,date,time,serviceId,reason:$('bookingReason').value||'Consulta',status:'pendiente'});save();closeDialog($('bookingModal'));$('agendaDate').value=date;renderAgenda();renderDashboard();toast('Cita agendada.')}
function discharge(id){const h=(state.hospitalizations[selectedPatientId]||[]).find(x=>x.id===id);if(!h)return;h.status='alta';h.alta={diagnosis:h.diagnosis,recommendations:'Control en 7 días'};save();renderFicha();toast('Alta registrada.')}
function init(){populate();$('agendaDate').value=DEFAULT_DATE;$('bookingDate').value=DEFAULT_DATE;$('todayLabel').textContent=fmt(DEFAULT_DATE);$('loginForm').onsubmit=e=>{e.preventDefault();if($('rut').value.replace(/\./g,'')==='22222222-2'&&$('password').value==='DemoVet2026!'){$('loginScreen').classList.add('hidden');$('app').classList.remove('hidden');renderDashboard()}else toast('Credenciales incorrectas.')};$('logoutDemo').onclick=()=>{$('app').classList.add('hidden');$('loginScreen').classList.remove('hidden')};document.querySelectorAll('.nav-item').forEach(b=>b.onclick=()=>go(b.dataset.view));document.querySelectorAll('[data-go]').forEach(b=>b.onclick=()=>go(b.dataset.go));$('menuToggle').onclick=()=>$('vetSidebar').classList.toggle('open');$('agendaDate').onchange=renderAgenda;$('vetFilter').onchange=renderAgenda;$('todayButton').onclick=()=>{$('agendaDate').value=DEFAULT_DATE;renderAgenda()};$('openBooking').onclick=()=>openBooking();$('bookingVet').onchange=refreshBookingTimes;$('bookingService').onchange=refreshBookingTimes;$('bookingDate').onchange=refreshBookingTimes;$('bookingForm').onsubmit=saveBooking;$('patientSearch').oninput=e=>renderPatients(e.target.value);$('patientSelect').onchange=e=>{selectedPatientId=+e.target.value;renderFicha()};$('historySearch').oninput=renderTimeline;document.querySelectorAll('[data-clinical-tab]').forEach(b=>b.onclick=()=>{document.querySelectorAll('[data-clinical-tab]').forEach(x=>x.classList.remove('active'));document.querySelectorAll('.clinical-tab').forEach(x=>x.classList.remove('active'));b.classList.add('active');$('clinical-'+b.dataset.clinicalTab).classList.add('active')});$('openConsultation').onclick=()=>openDialog('consultationModal');$('openHospitalization').onclick=$('openHospitalization2').onclick=()=>openDialog('hospitalModal');document.querySelectorAll('.close-dialog').forEach(b=>b.onclick=()=>closeDialog(b.closest('dialog')));document.querySelectorAll('dialog').forEach(d=>{d.addEventListener('click',e=>{if(e.target===d)closeDialog(d)});d.addEventListener('cancel',e=>{e.preventDefault();closeDialog(d)})});$('completeNext').onclick=()=>{const a=state.appointments.find(x=>x.date===DEFAULT_DATE&&x.status!=='completada');if(a){a.status='completada';save();renderDashboard();renderAgenda()}};renderAgenda();renderPatients();renderFicha()}
document.addEventListener('DOMContentLoaded',init);