# Generated by Django 6.0 on 2025-12-14 13:28

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuditoriaCaja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accion', models.CharField(choices=[('crear_venta', 'Crear Venta'), ('agregar_detalle', 'Agregar Detalle'), ('eliminar_detalle', 'Eliminar Detalle'), ('modificar_detalle', 'Modificar Detalle'), ('aplicar_descuento', 'Aplicar Descuento'), ('confirmar_pago', 'Confirmar Pago'), ('cancelar_venta', 'Cancelar Venta'), ('abrir_sesion', 'Abrir Sesión'), ('cerrar_sesion', 'Cerrar Sesión')], max_length=30)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('descripcion', models.TextField()),
                ('datos_anteriores', models.JSONField(blank=True, null=True)),
                ('datos_nuevos', models.JSONField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Auditoría de Caja',
                'verbose_name_plural': 'Auditorías de Caja',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='Caja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_apertura', models.DateTimeField(default=django.utils.timezone.now)),
                ('fecha_cierre', models.DateTimeField(blank=True, null=True)),
                ('monto_inicial', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('monto_final', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Caja',
                'verbose_name_plural': 'Cajas',
                'ordering': ['-fecha_apertura'],
            },
        ),
        migrations.CreateModel(
            name='DetalleVenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('servicio', 'Servicio'), ('insumo', 'Insumo')], max_length=10)),
                ('descripcion', models.CharField(max_length=255)),
                ('cantidad', models.DecimalField(decimal_places=2, default=1, max_digits=10)),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=12)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=12)),
                ('peso_paciente', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('dosis_calculada_ml', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('ml_contenedor', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('calculo_automatico', models.BooleanField(default=False)),
                ('stock_descontado', models.BooleanField(default=False)),
                ('fecha_descuento_stock', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Detalle de Venta',
                'verbose_name_plural': 'Detalles de Venta',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='MovimientoCaja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('ingreso', 'Ingreso'), ('egreso', 'Egreso')], max_length=10)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('concepto', models.CharField(max_length=200)),
                ('metodo_pago', models.CharField(choices=[('efectivo', 'Efectivo'), ('tarjeta', 'Tarjeta'), ('transferencia', 'Transferencia'), ('cheque', 'Cheque'), ('otro', 'Otro')], default='efectivo', max_length=20)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Movimiento de Caja',
                'verbose_name_plural': 'Movimientos de Caja',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='SesionCaja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_apertura', models.DateTimeField(default=django.utils.timezone.now)),
                ('fecha_cierre', models.DateTimeField(blank=True, null=True)),
                ('monto_inicial', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('monto_final_calculado', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('monto_final_contado', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('diferencia', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('observaciones_apertura', models.TextField(blank=True, null=True)),
                ('observaciones_cierre', models.TextField(blank=True, null=True)),
                ('esta_cerrada', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Sesión de Caja',
                'verbose_name_plural': 'Sesiones de Caja',
                'ordering': ['-fecha_apertura'],
            },
        ),
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_venta', models.CharField(editable=False, max_length=20, unique=True)),
                ('tipo_origen', models.CharField(choices=[('consulta', 'Consulta'), ('hospitalizacion', 'Hospitalización'), ('venta_libre', 'Venta Libre')], default='venta_libre', max_length=20)),
                ('estado', models.CharField(choices=[('pendiente', 'Cobro Pendiente'), ('pagado', 'Pagado'), ('cancelado', 'Cancelado')], default='pendiente', max_length=20)),
                ('subtotal_servicios', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('subtotal_insumos', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('descuento', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('metodo_pago', models.CharField(blank=True, choices=[('efectivo', 'Efectivo'), ('tarjeta', 'Tarjeta'), ('transferencia', 'Transferencia'), ('cheque', 'Cheque'), ('mixto', 'Mixto')], max_length=20, null=True)),
                ('fecha_pago', models.DateTimeField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Venta / Cobro',
                'verbose_name_plural': 'Ventas / Cobros',
                'ordering': ['-fecha_creacion'],
            },
        ),
    ]
