# Generated by Django 5.2.7 on 2025-11-04 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Caja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_caja', models.DateField()),
                ('valor_total', models.IntegerField()),
                ('valor_ins', models.FloatField()),
                ('metodo_pago', models.CharField(max_length=50)),
            ],
        ),
    ]
