# Generated by Django 5.2.7 on 2025-11-17 09:25

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caja', '0001_initial'),
        ('gestion', '0002_remove_documentomascota_mascota_delete_agenda_and_more'),
        ('hospital', '0002_rename_idins_insumo_idinventario_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='caja',
            name='id',
        ),
        migrations.RemoveField(
            model_name='caja',
            name='valor_ins',
        ),
        migrations.AddField(
            model_name='caja',
            name='consulta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestion.consulta'),
        ),
        migrations.AddField(
            model_name='caja',
            name='descripcion',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='caja',
            name='hospitalizacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hospital.hospitalizacion'),
        ),
        migrations.AddField(
            model_name='caja',
            name='idCaja',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='caja',
            name='num_operacion',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='caja',
            name='veterinario',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='caja',
            name='metodo_pago',
            field=models.CharField(choices=[('efectivo', 'Efectivo'), ('tarjetadeb', 'Debito'), ('tarjetacred', 'Credito'), ('transferencia', 'Transferencia')], max_length=50),
        ),
        migrations.AlterField(
            model_name='caja',
            name='valor_total',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterModelTable(
            name='caja',
            table='Caja',
        ),
        migrations.CreateModel(
            name='DetalleCaja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField(default=1)),
                ('Caja', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='caja.caja')),
                ('Insumo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospital.insumo')),
            ],
        ),
    ]
