# Generated by Django 6.0 on 2025-12-14 13:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('caja', '0001_initial'),
        ('clinica', '0001_initial'),
        ('inventario', '0001_initial'),
        ('pacientes', '0001_initial'),
        ('servicios', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='auditoriacaja',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, null=True, default=None),
        ),
        migrations.AddField(
            model_name='caja',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='detalleventa',
            name='insumo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventario.insumo'),
        ),
        migrations.AddField(
            model_name='detalleventa',
            name='servicio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='servicios.servicio'),
        ),
        migrations.AddField(
            model_name='movimientocaja',
            name='caja',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimientos', to='caja.caja'),
        ),
        migrations.AddField(
            model_name='sesioncaja',
            name='usuario_apertura',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sesiones_abiertas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sesioncaja',
            name='usuario_cierre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sesiones_cerradas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='auditoriacaja',
            name='sesion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='auditorias', to='caja.sesioncaja'),
        ),
        migrations.AddField(
            model_name='venta',
            name='consulta',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='venta', to='clinica.consulta'),
        ),
        migrations.AddField(
            model_name='venta',
            name='hospitalizacion',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='venta', to='clinica.hospitalizacion'),
        ),
        migrations.AddField(
            model_name='venta',
            name='paciente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ventas', to='pacientes.paciente'),
        ),
        migrations.AddField(
            model_name='venta',
            name='sesion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ventas', to='caja.sesioncaja'),
        ),
        migrations.AddField(
            model_name='venta',
            name='usuario_cobro',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ventas_cobradas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='venta',
            name='usuario_creacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ventas_creadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='detalleventa',
            name='venta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='caja.venta'),
        ),
        migrations.AddField(
            model_name='auditoriacaja',
            name='venta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='auditorias', to='caja.venta'),
        ),
        migrations.AddIndex(
            model_name='venta',
            index=models.Index(fields=['estado', 'fecha_creacion'], name='caja_venta_estado_f496fc_idx'),
        ),
        migrations.AddIndex(
            model_name='venta',
            index=models.Index(fields=['numero_venta'], name='caja_venta_numero__27db71_idx'),
        ),
    ]
