# Generated by Django 5.2.7 on 2025-12-09 03:37

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caja', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='caja',
            options={'ordering': ['-fecha_apertura'], 'verbose_name': 'Caja', 'verbose_name_plural': 'Cajas'},
        ),
        migrations.RemoveField(
            model_name='caja',
            name='fecha_caja',
        ),
        migrations.RemoveField(
            model_name='caja',
            name='metodo_pago',
        ),
        migrations.RemoveField(
            model_name='caja',
            name='valor_ins',
        ),
        migrations.RemoveField(
            model_name='caja',
            name='valor_total',
        ),
        migrations.AddField(
            model_name='caja',
            name='fecha_apertura',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='caja',
            name='fecha_cierre',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='caja',
            name='monto_final',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='caja',
            name='monto_inicial',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='caja',
            name='observaciones',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='caja',
            name='usuario',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='MovimientoCaja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('ingreso', 'Ingreso'), ('egreso', 'Egreso')], max_length=10)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('concepto', models.CharField(max_length=200)),
                ('metodo_pago', models.CharField(choices=[('efectivo', 'Efectivo'), ('tarjeta', 'Tarjeta'), ('transferencia', 'Transferencia'), ('cheque', 'Cheque'), ('otro', 'Otro')], default='efectivo', max_length=20)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now)),
                ('caja', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimientos', to='caja.caja')),
            ],
            options={
                'verbose_name': 'Movimiento de Caja',
                'verbose_name_plural': 'Movimientos de Caja',
                'ordering': ['-fecha'],
            },
        ),
    ]
