# Generated by Django 5.2.7 on 2025-12-12 11:51

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caja', '0002_alter_caja_options_remove_caja_fecha_caja_and_more'),
        ('clinica', '0011_consulta_servicios'),
        ('inventario', '0006_insumo_cantidad_pastillas_insumo_formato_and_more'),
        ('pacientes', '0004_remove_paciente_observaciones'),
        ('servicios', '0006_alter_servicioinsumo_insumo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SesionCaja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_apertura', models.DateTimeField(default=django.utils.timezone.now)),
                ('fecha_cierre', models.DateTimeField(blank=True, null=True)),
                ('monto_inicial', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('monto_final_calculado', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('monto_final_contado', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('diferencia', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('observaciones_apertura', models.TextField(blank=True, null=True)),
                ('observaciones_cierre', models.TextField(blank=True, null=True)),
                ('esta_cerrada', models.BooleanField(default=False)),
                ('usuario_apertura', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sesiones_abiertas', to=settings.AUTH_USER_MODEL)),
                ('usuario_cierre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sesiones_cerradas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Sesión de Caja',
                'verbose_name_plural': 'Sesiones de Caja',
                'ordering': ['-fecha_apertura'],
            },
        ),
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_venta', models.CharField(editable=False, max_length=20, unique=True)),
                ('tipo_origen', models.CharField(choices=[('consulta', 'Consulta'), ('hospitalizacion', 'Hospitalización'), ('venta_libre', 'Venta Libre')], default='venta_libre', max_length=20)),
                ('estado', models.CharField(choices=[('pendiente', 'Cobro Pendiente'), ('pagado', 'Pagado'), ('cancelado', 'Cancelado')], default='pendiente', max_length=20)),
                ('subtotal_servicios', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('subtotal_insumos', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('descuento', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('metodo_pago', models.CharField(blank=True, choices=[('efectivo', 'Efectivo'), ('tarjeta', 'Tarjeta'), ('transferencia', 'Transferencia'), ('cheque', 'Cheque'), ('mixto', 'Mixto')], max_length=20, null=True)),
                ('fecha_pago', models.DateTimeField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('consulta', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='venta', to='clinica.consulta')),
                ('hospitalizacion', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='venta', to='clinica.hospitalizacion')),
                ('paciente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ventas', to='pacientes.paciente')),
                ('sesion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ventas', to='caja.sesioncaja')),
                ('usuario_cobro', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ventas_cobradas', to=settings.AUTH_USER_MODEL)),
                ('usuario_creacion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ventas_creadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Venta / Cobro',
                'verbose_name_plural': 'Ventas / Cobros',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='DetalleVenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('servicio', 'Servicio'), ('insumo', 'Insumo')], max_length=10)),
                ('descripcion', models.CharField(max_length=255)),
                ('cantidad', models.DecimalField(decimal_places=2, default=1, max_digits=10)),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=12)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=12)),
                ('peso_paciente', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('dosis_calculada_ml', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('ml_contenedor', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('calculo_automatico', models.BooleanField(default=False)),
                ('stock_descontado', models.BooleanField(default=False)),
                ('fecha_descuento_stock', models.DateTimeField(blank=True, null=True)),
                ('insumo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventario.insumo')),
                ('servicio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='servicios.servicio')),
                ('venta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='caja.venta')),
            ],
            options={
                'verbose_name': 'Detalle de Venta',
                'verbose_name_plural': 'Detalles de Venta',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='AuditoriaCaja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accion', models.CharField(choices=[('crear_venta', 'Crear Venta'), ('agregar_detalle', 'Agregar Detalle'), ('eliminar_detalle', 'Eliminar Detalle'), ('modificar_detalle', 'Modificar Detalle'), ('aplicar_descuento', 'Aplicar Descuento'), ('confirmar_pago', 'Confirmar Pago'), ('cancelar_venta', 'Cancelar Venta'), ('abrir_sesion', 'Abrir Sesión'), ('cerrar_sesion', 'Cerrar Sesión')], max_length=30)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('descripcion', models.TextField()),
                ('datos_anteriores', models.JSONField(blank=True, null=True)),
                ('datos_nuevos', models.JSONField(blank=True, null=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('sesion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='auditorias', to='caja.sesioncaja')),
                ('venta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='auditorias', to='caja.venta')),
            ],
            options={
                'verbose_name': 'Auditoría de Caja',
                'verbose_name_plural': 'Auditorías de Caja',
                'ordering': ['-fecha'],
            },
        ),
        migrations.AddIndex(
            model_name='venta',
            index=models.Index(fields=['estado', 'fecha_creacion'], name='caja_venta_estado_f496fc_idx'),
        ),
        migrations.AddIndex(
            model_name='venta',
            index=models.Index(fields=['numero_venta'], name='caja_venta_numero__27db71_idx'),
        ),
    ]
