# Generated by Django 6.0 on 2025-12-14 13:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pacientes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hospitalizacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_ingreso', models.DateTimeField(auto_now_add=True)),
                ('fecha_alta', models.DateTimeField(blank=True, null=True)),
                ('motivo', models.TextField()),
                ('diagnostico', models.TextField(blank=True, null=True)),
                ('tratamiento', models.TextField(blank=True, null=True)),
                ('estado_hosp', models.CharField(choices=[('ingresado', 'Ingresado'), ('en_tratamiento', 'En Tratamiento'), ('recuperacion', 'En Recuperación'), ('alta', 'Alta')], default='ingresado', max_length=20)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('idMascota', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pacientes.paciente')),
            ],
            options={
                'verbose_name': 'Hospitalización',
                'verbose_name_plural': 'Hospitalizaciones',
                'ordering': ['-fecha_ingreso'],
            },
        ),
    ]
