# Generated by Django 5.2.7 on 2025-11-04 04:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gestion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Insumo',
            fields=[
                ('idIns', models.AutoField(primary_key=True, serialize=False)),
                ('medicamento', models.CharField(max_length=100)),
                ('dosis', models.FloatField()),
                ('valor_unitario', models.FloatField()),
                ('cantidad', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Hospitalizacion',
            fields=[
                ('idHospitalizacion', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_ingreso', models.DateField()),
                ('fecha_egreso', models.DateField()),
                ('motivo_hospitalizacion', models.TextField()),
                ('tratamiento', models.TextField()),
                ('telefono', models.CharField(max_length=15)),
                ('notas', models.TextField()),
                ('estado_hosp', models.CharField(choices=[('ingresado', 'Ingresado'), ('egresado', 'Egresado'), ('en tratamiento', 'En Tratamiento'), ('llamar duenio', 'Llamar Dueño'), ('alta', 'Alta')], default='ingresado', max_length=20)),
                ('idMascota', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.mascota')),
                ('idIns', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospital.insumo')),
            ],
        ),
    ]
