# Generated by Django 5.2.7 on 2025-11-17 14:16

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gestion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Insumo',
            fields=[
                ('idInventario', models.AutoField(primary_key=True, serialize=False)),
                ('medicamento', models.CharField(max_length=200)),
                ('categoria', models.CharField(blank=True, max_length=100, null=True)),
                ('sku', models.CharField(blank=True, max_length=100, null=True)),
                ('codigo_barra', models.CharField(blank=True, max_length=100, null=True)),
                ('presentacion', models.CharField(blank=True, max_length=150, null=True)),
                ('especie', models.CharField(blank=True, max_length=50, null=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('unidad_medida', models.CharField(blank=True, max_length=50, null=True)),
                ('precio_venta', models.FloatField(default=0)),
                ('margen', models.FloatField(default=0)),
                ('stock_actual', models.IntegerField(default=0)),
                ('stock_minimo', models.IntegerField(default=0)),
                ('stock_maximo', models.IntegerField(default=0)),
                ('almacenamiento', models.TextField(blank=True, null=True)),
                ('precauciones', models.TextField(blank=True, null=True)),
                ('contraindicaciones', models.TextField(blank=True, null=True)),
                ('efectos_adversos', models.TextField(blank=True, null=True)),
                ('dosis_ml', models.FloatField(blank=True, null=True)),
                ('peso_kg', models.FloatField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'Insumo',
                'ordering': ['medicamento'],
            },
        ),
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('idServicio', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('categoria', models.CharField(max_length=100)),
                ('precio', models.IntegerField(default=0)),
                ('duracion', models.IntegerField(default=0)),
                ('fecha_creacion', models.DateTimeField(default=django.utils.timezone.now)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'Servicio',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Hospitalizacion',
            fields=[
                ('idHospitalizacion', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_ingreso', models.DateField()),
                ('fecha_egreso', models.DateField()),
                ('motivo_hospitalizacion', models.TextField()),
                ('tratamiento', models.TextField()),
                ('telefono', models.CharField(max_length=15)),
                ('notas', models.TextField()),
                ('estado_hosp', models.CharField(choices=[('ingresado', 'Ingresado'), ('egresado', 'Egresado'), ('en tratamiento', 'En Tratamiento'), ('llamar duenio', 'Llamar Dueño'), ('alta', 'Alta')], default='ingresado', max_length=20)),
                ('idMascota', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.mascota')),
                ('idIns', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospital.insumo')),
            ],
        ),
        migrations.CreateModel(
            name='ServicioInsumo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField(default=1)),
                ('insumo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospital.insumo')),
                ('servicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospital.servicio')),
            ],
            options={
                'db_table': 'ServicioInsumo',
                'unique_together': {('servicio', 'insumo')},
            },
        ),
        migrations.AddField(
            model_name='servicio',
            name='insumos',
            field=models.ManyToManyField(related_name='servicios', through='hospital.ServicioInsumo', to='hospital.insumo'),
        ),
    ]
