# Generated by Django 5.2.7 on 2025-11-17 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='servicio',
            options={'ordering': ['nombre'], 'verbose_name': 'Servicio Veterinario', 'verbose_name_plural': 'Servicios Veterinarios'},
        ),
        migrations.RemoveField(
            model_name='servicio',
            name='insumos',
        ),
        migrations.AlterField(
            model_name='servicio',
            name='categoria',
            field=models.CharField(max_length=100, verbose_name='Categoría'),
        ),
        migrations.AlterField(
            model_name='servicio',
            name='descripcion',
            field=models.TextField(blank=True, null=True, verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='servicio',
            name='duracion',
            field=models.PositiveIntegerField(default=0, verbose_name='Duración (minutos)'),
        ),
        migrations.AlterField(
            model_name='servicio',
            name='fecha_actualizacion',
            field=models.DateTimeField(auto_now=True, verbose_name='Última Actualización'),
        ),
        migrations.AlterField(
            model_name='servicio',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Registro'),
        ),
        migrations.AlterField(
            model_name='servicio',
            name='nombre',
            field=models.CharField(max_length=150, verbose_name='Nombre del Servicio'),
        ),
        migrations.AlterField(
            model_name='servicio',
            name='precio',
            field=models.PositiveIntegerField(default=0, verbose_name='Precio del Servicio'),
        ),
    ]
