# Generated by Django 5.2.7 on 2025-11-17 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='insumo',
            old_name='idIns',
            new_name='idInventario',
        ),
        migrations.RemoveField(
            model_name='insumo',
            name='cantidad',
        ),
        migrations.RemoveField(
            model_name='insumo',
            name='dosis',
        ),
        migrations.RemoveField(
            model_name='insumo',
            name='valor_unitario',
        ),
        migrations.AddField(
            model_name='insumo',
            name='almacenamiento',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='insumo',
            name='categoria',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='insumo',
            name='codigo_barra',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='insumo',
            name='contraindicaciones',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='insumo',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='insumo',
            name='efectos_adversos',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='insumo',
            name='especie',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='insumo',
            name='margen',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='insumo',
            name='precauciones',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='insumo',
            name='precio_compra',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='insumo',
            name='precio_venta',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='insumo',
            name='presentacion',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='insumo',
            name='proveedor',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='insumo',
            name='sku',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='insumo',
            name='stock_actual',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='insumo',
            name='stock_maximo',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='insumo',
            name='stock_minimo',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='insumo',
            name='unidad_medida',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
