# Generated by Django 5.2.7 on 2025-11-17 10:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0003_proveedor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insumo',
            name='proveedor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hospital.proveedor'),
        ),
    ]
