# Generated by Django 5.2.7 on 2025-11-17 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0004_alter_insumo_proveedor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='insumo',
            name='proveedor',
        ),
        migrations.AddField(
            model_name='insumo',
            name='ml',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='Proveedor',
        ),
    ]
