# Generated by Django 5.2.7 on 2025-12-06 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0004_paciente_color_paciente_fecha_ultimo_control_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='microchip',
            field=models.CharField(blank=True, help_text='Número de microchip (opcional)', max_length=50, null=True),
        ),
    ]
