# Generated by Django 5.2.7 on 2025-11-17 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0005_remove_insumo_proveedor_insumo_ml_delete_proveedor'),
    ]

    operations = [
        migrations.AddField(
            model_name='insumo',
            name='rangos_dosis',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
