# Generated by Django 5.2.7 on 2025-11-17 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0006_insumo_rangos_dosis'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='insumo',
            name='ml',
        ),
        migrations.RemoveField(
            model_name='insumo',
            name='rangos_dosis',
        ),
        migrations.AddField(
            model_name='insumo',
            name='dosis_ml',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='insumo',
            name='peso_kg',
            field=models.FloatField(default=1),
        ),
    ]
