# Generated by Django 5.2.7 on 2025-12-07 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0006_paciente_edad_anos_paciente_edad_meses_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paciente',
            name='edad',
        ),
        migrations.AddField(
            model_name='paciente',
            name='fecha_ultima_modificacion',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='color',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='edad_anos',
            field=models.IntegerField(blank=True, null=True, verbose_name='Edad en años'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='edad_meses',
            field=models.IntegerField(blank=True, null=True, verbose_name='Edad en meses'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='especie',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='fecha_ultimo_control',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='microchip',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='sexo',
            field=models.CharField(choices=[('M', 'Macho'), ('H', 'Hembra')], max_length=1),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='ultimo_peso',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
