# Generated by Django 5.2.7 on 2025-12-07 08:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0007_remove_paciente_edad_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='propietario',
            options={'ordering': ['apellido', 'nombre'], 'verbose_name': 'Propietario', 'verbose_name_plural': 'Propietarios'},
        ),
    ]
