# Generated by Django 5.2.7 on 2025-11-17 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0007_remove_insumo_ml_remove_insumo_rangos_dosis_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('tipo', models.CharField(max_length=50)),
                ('precio', models.FloatField()),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
