# Generated by Django 5.2.7 on 2025-11-17 13:33

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0008_servicio'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='servicio',
            options={'ordering': ['nombre'], 'verbose_name': 'Servicio Veterinario', 'verbose_name_plural': 'Servicios Veterinarios'},
        ),
        migrations.RemoveField(
            model_name='servicio',
            name='id',
        ),
        migrations.RemoveField(
            model_name='servicio',
            name='tipo',
        ),
        migrations.AddField(
            model_name='servicio',
            name='categoria',
            field=models.CharField(default='', max_length=100, verbose_name='Categoría'),
        ),
        migrations.AddField(
            model_name='servicio',
            name='duracion',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='servicio',
            name='fecha_actualizacion',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='servicio',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='servicio',
            name='idServicio',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='servicio',
            name='descripcion',
            field=models.TextField(blank=True, null=True, verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='servicio',
            name='nombre',
            field=models.CharField(max_length=150, verbose_name='Nombre del Servicio'),
        ),
        migrations.AlterField(
            model_name='servicio',
            name='precio',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterModelTable(
            name='servicio',
            table='Servicio',
        ),
    ]
