# Generated by Django 5.2.7 on 2025-12-07 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0008_alter_propietario_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='insumo',
            name='ml_contenedor',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='ML en Contenedor'),
        ),
    ]
