# Generated by Django 5.2.7 on 2025-12-07 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0009_insumo_ml_contenedor'),
    ]

    operations = [
        migrations.AddField(
            model_name='insumo',
            name='tipo',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Tipo de Producto'),
        ),
    ]
