# Generated by Django 5.2.7 on 2025-11-17 13:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0009_alter_servicio_options_remove_servicio_id_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='servicio',
            options={},
        ),
        migrations.AlterField(
            model_name='servicio',
            name='categoria',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='servicio',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='servicio',
            name='nombre',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterModelTable(
            name='servicio',
            table=None,
        ),
        migrations.CreateModel(
            name='ServicioInsumo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(default=1)),
                ('insumo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospital.insumo')),
                ('servicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospital.servicio')),
            ],
            options={
                'unique_together': {('servicio', 'insumo')},
            },
        ),
        migrations.AddField(
            model_name='servicio',
            name='insumos',
            field=models.ManyToManyField(related_name='servicios', through='hospital.ServicioInsumo', to='hospital.insumo'),
        ),
    ]
