# Generated by Django 5.2.7 on 2025-12-08 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0010_insumo_tipo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='insumo',
            name='almacenamiento',
        ),
        migrations.RemoveField(
            model_name='insumo',
            name='codigo_barra',
        ),
        migrations.RemoveField(
            model_name='insumo',
            name='margen',
        ),
        migrations.RemoveField(
            model_name='insumo',
            name='presentacion',
        ),
        migrations.RemoveField(
            model_name='insumo',
            name='stock_maximo',
        ),
        migrations.RemoveField(
            model_name='insumo',
            name='stock_minimo',
        ),
        migrations.RemoveField(
            model_name='insumo',
            name='unidad_medida',
        ),
        migrations.AddField(
            model_name='insumo',
            name='ultimo_ingreso',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='insumo',
            name='ultimo_movimiento',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
