# Generated by Django 5.2.7 on 2025-12-08 11:20

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0011_remove_insumo_almacenamiento_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='insumo',
            name='tipo_ultimo_movimiento',
            field=models.CharField(blank=True, choices=[('entrada', 'Entrada de Stock'), ('salida', 'Salida de Stock'), ('venta', 'Venta'), ('ajuste_manual', 'Ajuste Manual'), ('registro_inicial', 'Registro Inicial')], max_length=20, null=True, verbose_name='Tipo de Último Movimiento'),
        ),
        migrations.AlterField(
            model_name='insumo',
            name='fecha_creacion',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de Registro'),
        ),
        migrations.AlterField(
            model_name='insumo',
            name='ultimo_ingreso',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Última Entrada de Stock'),
        ),
        migrations.AlterField(
            model_name='insumo',
            name='ultimo_movimiento',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Último Movimiento'),
        ),
    ]
