# Generated by Django 5.2.7 on 2025-12-08 12:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0012_insumo_tipo_ultimo_movimiento_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='insumo',
            name='usuario_ultimo_movimiento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimientos_insumos', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='insumo',
            name='tipo_ultimo_movimiento',
            field=models.CharField(blank=True, choices=[('entrada', 'Entrada de Stock'), ('venta', 'Venta'), ('consulta', 'Uso en Consulta'), ('hospitalizacion', 'Uso en Hospitalización'), ('ajuste_manual', 'Ajuste Manual'), ('devolucion', 'Devolución'), ('registro_inicial', 'Registro Inicial')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='insumo',
            name='ultimo_ingreso',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='insumo',
            name='ultimo_movimiento',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
