# Generated by Django 5.2.7 on 2025-12-08 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0013_insumo_usuario_ultimo_movimiento_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='insumo',
            name='categoria',
        ),
    ]
