# Generated by Django 5.2.7 on 2025-12-08 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0014_remove_insumo_categoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insumo',
            name='tipo_ultimo_movimiento',
            field=models.CharField(blank=True, choices=[('entrada', 'Entrada de Stock'), ('salida', 'Salida de Stock'), ('venta', 'Venta'), ('consulta', 'Uso en Consulta'), ('hospitalizacion', 'Uso en Hospitalización'), ('ajuste_manual', 'Ajuste Manual'), ('devolucion', 'Devolución'), ('registro_inicial', 'Registro Inicial')], max_length=20, null=True),
        ),
    ]
