# Generated by Django 5.2.7 on 2025-12-08 19:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0015_alter_insumo_tipo_ultimo_movimiento'),
    ]

    operations = [
    ]
