# Generated by Django 6.0 on 2025-12-17 12:22

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroHistorico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_evento', models.DateTimeField(db_index=True, default=django.utils.timezone.now, help_text='Momento en que ocurrió el evento', verbose_name='Fecha del Evento')),
                ('entidad', models.CharField(choices=[('inventario', 'Inventario'), ('servicio', 'Servicio'), ('paciente', 'Paciente')], db_index=True, help_text='Tipo de entidad afectada', max_length=20, verbose_name='Entidad')),
                ('objeto_id', models.PositiveIntegerField(db_index=True, help_text='ID del registro afectado en su tabla', verbose_name='ID del Objeto')),
                ('tipo_evento', models.CharField(choices=[('creacion', 'Creación'), ('modificacion_informacion', 'Modificación de Información'), ('activacion', 'Activación'), ('desactivacion', 'Desactivación'), ('ingreso_stock', 'Ingreso de Stock'), ('salida_stock', 'Salida de Stock'), ('actualizacion_precio', 'Actualización de Precio'), ('cambio_precio_servicio', 'Cambio de Precio de Servicio'), ('cambio_duracion', 'Cambio de Duración'), ('cambio_categoria', 'Cambio de Categoría'), ('cambio_propietario', 'Cambio de Propietario'), ('actualizacion_peso', 'Actualización de Peso'), ('actualizacion_antecedentes', 'Actualización de Antecedentes Médicos'), ('modificacion_datos_basicos', 'Modificación de Datos Básicos')], db_index=True, help_text='Clasificación del evento', max_length=50, verbose_name='Tipo de Evento')),
                ('descripcion', models.TextField(help_text='Descripción legible del evento para usuarios', verbose_name='Descripción')),
                ('datos_cambio', models.JSONField(blank=True, help_text='Estructura JSON con valores anteriores/nuevos y metadatos', null=True, verbose_name='Datos del Cambio')),
                ('criticidad', models.CharField(choices=[('baja', 'Baja'), ('media', 'Media'), ('alta', 'Alta'), ('critica', 'Crítica')], db_index=True, default='media', help_text='Nivel de importancia del evento', max_length=10, verbose_name='Criticidad')),
                ('usuario', models.ForeignKey(blank=True, help_text='Usuario que realizó el cambio (null para cambios automáticos)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eventos_historicos', to=settings.AUTH_USER_MODEL, verbose_name='Usuario Responsable')),
            ],
            options={
                'verbose_name': 'Registro Histórico',
                'verbose_name_plural': 'Registros Históricos',
                'db_table': 'registro_historico',
                'ordering': ['-fecha_evento'],
                'indexes': [models.Index(fields=['entidad', 'objeto_id', '-fecha_evento'], name='registro_hi_entidad_239db8_idx'), models.Index(fields=['criticidad', '-fecha_evento'], name='registro_hi_critici_b1f8d2_idx'), models.Index(fields=['usuario', '-fecha_evento'], name='registro_hi_usuario_99aab6_idx')],
            },
        ),
    ]
